# Update as of: March 9, 2026

## Author: Sandy G Cabanes
## Role: Sole Contributor (Volunteer)
## Date: March 2026
## Response Dates: September 2025 to March 2026
## Licensed Under MIT

"""
## This is preliminary work for automated cleaning.
## Will make sure to update the csv_raw.csv file after closing the survey.
"""

"""
# Notes:  all columns that are common in both 2024 and 2025-2026 runs for comparability:

- comparable single_response items: "country", "city_ph", "city_non_ph", "gender", "age", "educstat", "employertype", "industry", "salary", , "typework", "sitework", "datarole",  "sizeteam"

- comparable multi-response: "digitools", "successmethod", "restofrole",  "hardware", "dep_init", "volunteer", "spneeds", "otherfb"
 
- not exactly comparable due to change in choices or question phrasing: "careerstg", "ingestion", "transform", "warehs", "orchest", "busint", "cloudplat", "generaltools", "whatused"

- new single_response items: "have_comp_degree",  "comp_related_degree", "how_long_in_salary", "typework", "shift_schedule", "side_gig", "satisfaction", "ai_work", "ai_study"

- new multi_response items: "storage", "ai_tools"

- new open-text response items: "attended_inperson", "attended_online"

- deleted: 
- - best project, worksame and workcity (not in 2024 Tableau report due to either conflicting answers or redundant answers)
- - data catalogs, non-cloud platforms, reverse etl, data quality, hosted notebook, (due to very low responses)
- - comms, depwebsite, depwebres, converted to one multiple response question used for dep awareness

- added after processing:  resp_id with 2025-, age_grp, salary_broader for plotly breaks
"""

In [1]:
# 0. Imports & Config
# ~~~~~~~~~~~~~~~~~~~~~~~~~
import pandas as pd
import unicodedata
from pathlib import Path
import numpy as np
import csv # used in apply_lookup function

In [22]:
# 0. Create Directories
# Store all lookup files for single-response columns and exploded multi-response csv files
lookup_dir = Path("lookup_dir")
lookup_dir.mkdir(exist_ok=True)

# Store all parquet files
parquet_outputs_dir = Path("parquet_outputs_dir")
parquet_outputs_dir.mkdir(exist_ok=True)

# Store all the outputs as csv so cleaning can be split into modules
csv_outputs_dir = Path("csv_outputs_dir")
csv_outputs_dir.mkdir(exist_ok=True)

# Copy of all the final outputs for data model
final_outputs_dir = Path("final_outputs_dir")
final_outputs_dir.mkdir(exist_ok=True)

# Store preliminary unique values
unique_dir = Path("unique_dir")
unique_dir.mkdir(exist_ok=True)

# Store all csv and map files using country and city columns
location_dir = Path("location_dir")
location_dir.mkdir(exist_ok = True)

##  Lineage

- Raw file  
  - csv_raw.csv -> df_raw
  - df_raw (cleaned) <- df_raw

- Single‑response family  
  - df_single_no_grps <- df_raw[single_cols_no_grps].copy()  
  - df_single_with_grps <- df_single_no_grps.copy()  
  - df_possible_dups <- df_likely_dups that have a score == 1
  - df_sim_raw <- df_single_no_grps.copy()
  - df_sim_sorted <- df_sim_raw

- Multi‑response family  
  - csv_raw.csv -> df_raw_multi -> clean MS Fabric, clean and standardize None responses
  - df_multi <- df_raw_multi[["resp_id"] + multi_response_cols].copy()
  - datamasters_count <- df_multi_copy
  - df_exploded = explode_and_lookup(df_raw, col) -> saved to csv as {col}_exploded.csv
  - df_exploded_cleaned 
  - df_merged_dups = df_possible_duplicates.merge()

- Location family  
  - df_loc_new <- df_single_with_groups
  - df_ph_grp, df_non_ph_grp <- df_loc_new 
  - overseas <- df_ph_grp 
  - df_ph_geo, df_non_ph_geo <- df_ph_grp, df_non_ph_grp
  - df_ph_geo_clean <- df_ph_geo
  - df_non_ph_geo_clean <- df_non_ph_geo
  - df_all_geo_clean <- df_ph_geo_clean, df_non_ph_geo_clean

-  Data mart family  
    - survey2026.duckdb
    - survey.sqlite
    - for_tableau.xls

# REMOVE TEST RUN FIRST!!!

In [11]:
# 1. Load Raw Data and Rename Columns (Raw -> Transformed)
# IMPORTANT: Remove the test runs first before saving as csv_raw.csv
df_raw= pd.read_csv(
    "csv_raw.csv",
    sep=",",
    quotechar='"',
    engine="python",
    encoding="utf-8-sig"
)

df_raw = df_raw.drop(columns = ['Timestamp', 'Email (Optional)  ', 'End of survey'])

In [ ]:
# 1a. Check the headers
headers_raw = df_raw.columns.to_list()
headers_raw

In [12]:
# 1b. Rename Columns (Raw → Transformed)
# columns = rename_map dictionary

rename_map = {
    "Country of Residence, current" : "country", #new
    "City of Residence, current": "city",
    "PHILIPPINE City of Residence, current (Please scroll to see all options.  If municipality, please write in Other - ______.   If not in the Philippines, please choose 'Not applicable' .)" : "city_ph",
    'NON-PHILIPPINE City of Residence (Choose Not Applicable if you are currently in the Philippines)' : "city_non_ph",
    "Gender": "gender",
    "Age (Please enter a number)": "age",
    "Latest education status": "educstat",
    "Do you have a Computer or Data-Related degree? ": "have_comp_degree", #new
    "If you have a Computer-Related degree, or Data-Related degree,  please indicate the degree below. \n(Otherwise, please choose Not Applicable, first button.)" : "comp_related_degree", #new
    "Choose the digital learning platforms or tools you are currently using for data-related learning:": "digitools",
    "What best describes the CURRENT STAGE of your data career?" : "careerstg",
    "Thinking of your most recent job search, which platform or method gave you the most success?": "successmethod",
    "Type of employer (Please select one option that best describes your current employment situation.)" : "employertype",
    "What Industry currently working in:": "industry",
    "Monthly Salary Range (Or monthly income from main source) If paid per project, please approximate monthly equivalent." : "salary",
    "How long have you been in the current salary range or monthly income range?" : "how_long_in_salary",  #new
    "What is your current Type of Work?": "typework", #new 
    "What is your current Work Site situation?": "sitework",
    "If working and in the Philippines, what is your working shift schedule most of the time? (If not in the Philippines, choose Not Applicable.)" : "shift_schedule",  #new
    "What best describes MAJORITY of your day-to-day role? (More than 50% of your role)": "datarole", #uncategorized in 2024
    "What other descriptions comprise the REST of your role? (Click all that apply)": "restofrole", #uncategorized in 2024
    "Thinking of the past 12 months in terms of side gigs or side hustles, which one applies to you?" : "side_gig", #new
    "On a scale of 1 to 10, how satisfied are you with your current data-related role or data career?  (1 - Not Satisfied At All, 10 - Extremely Satisfied)" : "satisfaction", #new
    "What is the size of your Data Team?": "sizeteam",
    "What are the data INGESTION tools you currently use? ": "ingestion",
    "What are the data TRANSFORMATION tools you currently use?  ": "transform",
    "What are the DATA LAKES OR OBJECT STORAGE SERVICES you currently use?" : "storage", #new
    "What are the data WAREHOUSES or RELATIONAL DATABASES that you currently use?   ": "warehs",
    "What are the data ORCHESTRATION tools you currently use?  ": "orchest",
    "What are the BUSINESS INTELLIGENCE tools you currently use? ": "busint",
    "What are the CLOUD-NATIVE DATA PLATFORMS you currently use?" : "cloudplat",
    "Which of the following \nNON-CODING-LANGUAGE DATA TOOLS OR PRODUCTIVITY TOOLS \ndo you use on a regular basis? Choose all that apply.": "generaltools",
    "Which of the following CODING LANGUAGES OR TOOLS do you use on a regular basis? Choose all that apply.": "whatused",
    "Thinking of WORK, do you currently use AI in your work?": "ai_work", #new
    "Thinking of STUDIES or UPSKILLING, do you currently use AI for study?": "ai_study", #new
    "If you answered Yes to use of AI at work or for study, please choose which AI tools you currently use.  (Choose Not Applicable if you do not use AI.)" : "ai_tools", # revised
    "What hardware do you currently use for data?": "hardware",
    "Which of the following DEP initiatives and channels are you aware of? Choose all that apply." : "dep_init", #revised
    "Any specific tasks, skills, knowledge or resources you are willing to contribute to the group as of today?": "volunteer",
    "Any specific needs you are trying to address by joining DEP Facebook group?" : "spneeds",
    "Thinking of data-related communities, what other Facebook communities do you follow?": "otherfb",
    'In the Past 12 months, what was the most recent DEP or data-related meet-up, hackathon, convention, that you attended IN PERSON? (Maximum 50 characters.  If none, it\'s ok, you can type "None")': "attended_inperson", #new
    'In the Past 12 months, what was the most recent DEP or data-related activity that you attended ONLINE? (E.g. discord event, free webinar, etc.   Maximum 50 characters.  If none, it\'s ok, you can type "None")' : "attended_online" #new
}


df_raw.rename(columns=rename_map, inplace=True)

In [ ]:
#1c. Check mapped headers
headers_revised= df_raw.columns.to_list()
headers_revised

In [13]:
#1d. Column data types
df_raw.info()

# Result as of March 5: n1732 total, n763 working

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1732 entries, 0 to 1731
Data columns (total 42 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   country              1732 non-null   object
 1   city_ph              1732 non-null   object
 2   city_non_ph          1715 non-null   object
 3   gender               1732 non-null   object
 4   age                  1732 non-null   int64
 5   educstat             1732 non-null   object
 6   have_comp_degree     1732 non-null   object
 7   comp_related_degree  1729 non-null   object
 8   digitools            1731 non-null   object
 9   careerstg            1732 non-null   object
 10  successmethod        763 non-null    object
 11  employertype         763 non-null    object
 12  industry             763 non-null    object
 13  salary               763 non-null    object
 14  how_long_in_salary   763 non-null    object
 15  typework             763 non-null    object
 16  sitework             763 non-null    object
 17  shift_schedule       763 non-null    object
 18  datarole             763 non-null    object
 19  restofrole           763 non-null    object
 20  side_gig             763 non-null    object
 21  satisfaction         763 non-null    float64
 22  sizeteam             763 non-null    object
 23  ingestion            763 non-null    object
 24  transform            763 non-null    object
 25  storage              763 non-null    object
 26  warehs               763 non-null    object
 27  orchest              763 non-null    object
 28  busint               763 non-null    object
 29  cloudplat            759 non-null    object
 30  generaltools         1732 non-null   object
 31  whatused             1732 non-null   object
 32  ai_work              1732 non-null   object
 33  ai_study             1732 non-null   object
 34  ai_tools             1732 non-null   object
 35  hardware             1732 non-null   object
 36  dep_init             1732 non-null   object
 37  volunteer            1716 non-null   object
 38  spneeds              1732 non-null   object
 39  otherfb              1731 non-null   object
 40  attended_inperson    315 non-null    object
 41  attended_online      500 non-null    object
dtypes: float64(1), int64(1), object(40)
memory usage: 568.4+ KB

In [ ]:
# 2. First Global Cleaning (Inline)
# Fillna, normalize font, strip, collapse spaces, title-case specific columns, 
# Replace Other with blanks, replace 0 age with min age, cap at 95

# Fillna, normalize font ex. ñ, strip, split
for col in df_raw.select_dtypes(include="object").columns:
    # Normalize, strip, collapse spaces
    df_raw[col] = (
        df_raw[col]
        .fillna("Not Applicable")
        .astype(str)
        .str.replace(r'[\u2010-\u2015]', '-', regex=True)
        .str.replace("â€“", "-", regex=False)
        .apply(lambda v: " ".join(
            unicodedata.normalize("NFKC", v.replace("ñ", "n")).strip().split()
        ))
    )
    # Title-case specific columns (For UK, KSA, etc. handle in the lookup portion to revert)
    if col in ["country", "city_ph", "city_non_ph", "datarole", "rest_of_role", "industry"]:
        df_raw[col] = df_raw[col].str.title()

# Replace strings that start with 'Other' with blanks
for col in df_raw.select_dtypes(include="object").columns:
     df_raw[col] = df_raw[col].apply(lambda v: "" if v.startswith("Other") else v)

# Replace age of 0 with min age, and cap at 95
valid_min_age = df_raw.loc[df_raw["age"] > 0, "age"].min()
df_raw["age"] = df_raw["age"].replace(0, valid_min_age)

max_age = df_raw["age"].max()
df_raw["age"] = df_raw["age"].apply(lambda x: max_age if x > 95 else x)

print ("First global cleaning done.")

First global cleaning done.

In [ ]:
#2a. Check after first global cleaning Or Open in Data Wrangler
df_raw.head()

In [16]:
# 3. Add resp_id and resp_id_rand to df_raw after first global cleaning
# Add resp_id
if "resp_id" not in df_raw.columns:
    df_raw.insert(0, "resp_id", range(1, len(df_raw) + 1))

# Add resp_id_rand    
import secrets

def generate_ids(n):
    ids = set()
    # Running the loop until the set contains the required number of unique IDs
    while len(ids) < n:
        # Creating a random 6-character hex string
        new_id = f"2025-{secrets.token_hex(3)}"
        ids.add(new_id)
    return list(ids)

# Assigning the unique list to the dataframe column
df_raw['resp_id_rand'] = generate_ids(len(df_raw))

In [ ]:
#3a. Check in Data Wrangler → export as df_raw.parquet
df_raw.head()

In [ ]:
#3b. Count empty strings and null values or isna and print only those with values
# empty_counts series: Count empty strings - this will include the "" replacements above
empty_counts = (df_raw == "").sum()
empty_columns_only = empty_counts[empty_counts > 0] #only the ones with values
print("\n\nEmpty strings", "~"*20)
if not empty_columns_only.empty:
    print(empty_columns_only)
else:
    print("No empty strings found in any column.")

# nan_counts series: Count NaN / Null values -- expect satisfaction to be total n minus working n
nan_counts = df_raw.isna().sum()
nan_columns_only = nan_counts[nan_counts > 0] #only the ones with values
print("\n\nNaN / Null values", "~"*20)
if not nan_columns_only.empty:
    print(nan_columns_only)
else:
    print("No NaN values found in any column.")

# Calculate NaN and empty cells 
combined_counts = df_raw.apply(
    lambda col: (
        col.isna() | 
        (col.astype(str).str.strip() == "")
    ).sum()
)
combined_only  = combined_counts[combined_counts > 0] #only the ones with values
print("\n\nCombined NaN or blanks", "~"*20)
if not combined_only.empty:
    print(combined_only)

# Result as of March 5:datarole (30), restofrole(29), satisfaction (969), transform(2)

Empty strings ~~~~~~~~~~~~~~~~~~~~
datarole      30
restofrole    29
transform      2
dtype: int64


NaN / Null values ~~~~~~~~~~~~~~~~~~~~
satisfaction    969
dtype: int64


Combined NaN or blanks ~~~~~~~~~~~~~~~~~~~~
datarole         30
restofrole       29
satisfaction    969
transform         2
dtype: int64

In [33]:
# 3c. Replace all empty strings and null values with "Not Applicable"
# Clean whitespace and empty strings
df_raw = df_raw.replace(r'^\s*$', "Not Applicable", regex=True)

# Clean technical Nulls (NaN)
df_raw = df_raw.fillna("Not Applicable")

# Special treatment for satisfaction, that requires numeric values
df_raw["satisfaction"] = df_raw["satisfaction"].apply(lambda x: 999 if x == "Not Applicable" else x)

In [ ]:
df_raw

In [ ]:
# If country is not Philippines, check if city_non_ph is Not Applicable or a Philippine city

df_nonph =df_raw[df_raw['country'] != 'Philippines'][['resp_id', 'country', 'city_non_ph']]
nonphlist =sorted(list(df_nonph['city_non_ph'].unique()))
print("Before cleaning non ph cities", "~"*20)
print (nonphlist)

# Ok, nonph cities are not Philippine cities.  

# Change the 'Not Applicable' to 'Prefer Not To Say'
filter_nonph = (df_raw['country'] != 'Philippines') & (df_raw['city_non_ph'] == 'Not Applicable')
df_raw.loc[filter_nonph, 'city_non_ph'] = 'Prefer Not To Say'

# Check again
df_nonph =df_raw[df_raw['country'] != 'Philippines'][['resp_id', 'country', 'city_non_ph']]
nonphlist =sorted(list(df_nonph['city_non_ph'].unique()))
print("After cleaning non ph cities", "~"*20)
print (nonphlist)

Before cleaning non ph cities ~~~~~~~~~~~~~~~~~~~~
['Abu Dhabi, United Arab Emirates', 'Accra', 'Alexandria', 'Amman', 'Bangkok', 'Barishal', 'Benin City', 'Cairo', 'Cape Town', 'Cerro De Pasco', 'Cheongju City', 'Diplo', 'Douala', 'Dubai', 'Ho Chi Minh', 'Jeddah', 'Kansas', 'Kathmandu', 'Kinshasa', 'Ksa', 'Kuala Lumpur', 'Lagos', 'Lagos State', 'London', 'Newcastle', 'Not Applicable', 'Oslo', 'Pasco', 'Phnom Penh', 'Prefer Not To Say', 'Regina', 'Riyadh', "Sana'A", 'Soroti City Uganda', 'Sydney', 'Uae', 'Ughelli']
After cleaning non ph cities ~~~~~~~~~~~~~~~~~~~~
['Abu Dhabi, United Arab Emirates', 'Accra', 'Alexandria', 'Amman', 'Bangkok', 'Barishal', 'Benin City', 'Cairo', 'Cape Town', 'Cerro De Pasco', 'Cheongju City', 'Diplo', 'Douala', 'Dubai', 'Ho Chi Minh', 'Jeddah', 'Kansas', 'Kathmandu', 'Kinshasa', 'Ksa', 'Kuala Lumpur', 'Lagos', 'Lagos State', 'London', 'Newcastle', 'Oslo', 'Pasco', 'Phnom Penh', 'Prefer Not To Say', 'Regina', 'Riyadh', "Sana'A", 'Soroti City Uganda', 'Sydney', 'Uae', 'Ughelli']

In [ ]:
# Open in Data Wrangler
df_nonph

In [ ]:
# If country is Philippines, check 
df_ph = df_raw[df_raw['country'] == 'Philippines'][['resp_id', 'country', 'city_ph', 'city_non_ph']]
df_ph # Open in Data Wrangler

In [35]:
# 3c. Export df_raw to parquet_outputs_dir
df_raw.to_parquet(parquet_outputs_dir/ "df_raw.parquet", index=False)
print("Date and Time:", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print("df_raw.parquet created. Global cleaning done.")

Date and Time: 2026-03-09 16:22:29
df_raw.parquet created. Global cleaning done.

# Handle single-response columns first
- single_cols_no_grps -> single_cols_non_numeric -> write unique_dir / "unique_single.txt"
- create starter csv for lookup with "raw" column -> copy to lookup_dir -> manually add "clean" column

In [49]:
# 4a. Define single response columns for lookups
# This section uses df_single_no_grps - 23 columns
# Later this will be split into three types of cleaning: direct, special and manual
single_cols_no_grps = [
    "resp_id", "country", "city_ph", "city_non_ph", "gender", "age", "educstat", "have_comp_degree", "comp_related_degree", "careerstg", "employertype", "industry", "salary", "how_long_in_salary", "typework", "sitework", "shift_schedule", "datarole", "side_gig", "satisfaction", "sizeteam", "ai_work", "ai_study", "resp_id_rand"
]

df_single_no_grps = df_raw[single_cols_no_grps].copy()

In [ ]:
# 4a2. Print out to terminal all unique values
# Check unique values first except resp_id  
# Write all unique values to a single file except resp_id, age

single_columns_non_numeric = [col for col in df_single_no_grps.columns if col not in ['resp_id', 'age', 'resp_id_rand', 'satisfaction']]

with open(unique_dir / "unique_single.txt", "w", encoding="utf-8") as f:
    for col in single_columns_non_numeric:
        f.write(f"{col}\n\n")
        for val in df_single_no_grps[col].dropna().unique():
            f.write(f"{val}\n")
        f.write("\n")
        
print("unique_single.txt created.  Inspect unique values.")
with open(unique_dir / "unique_single.txt", "r", encoding="utf-8") as f:
    print(f.read())
print("Date and Time: ", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

unique_single.txt created.  Inspect unique values.
country

Philippines
United Kingdom
Norway
Cameroon
Cambodia
Thailand
Pakistan
United Arab Emirates
Canada
Nepal
United States
Uae
Nigeria
Jordan
Egypt
Ksa
South Africa
Uganda
Congo
South Korea
Malaysia
Bangladesh
Yemen
Saudi Arabia
Peru
Perú
Kenya
Algeria
Vietnam
Ghana
India
Spain

city_ph

Pampanga
Binan
Mandaluyong
San Quintin
Taguig
Not Applicable
Aleosan
Dasmarinas
Muntinlupa
Quezon City
Pasig
Caloocan
Davao
Paranaque
Manila
Bacolod
Makati
Batangas
Zamboanga
Roxas
Las Pinas
La Pinas
Ozamiz City
Cavite
Calamba
Binalonan
Bulacan
Imus
Cebu
Tanza
Baliwag
Lake Sebu, South Cotabato
La Union
Camarines Sur
Calbayog Samar
Cagayan De Oro
Calbayog City
Laguna
Roxas City
San Fernando
Davao Del Norte
Surigao City
San Pablo
Bukidnon
Tarlac
Rizal
Iloilo
Valencia City Bukidnon
Cabuyao
El Salvador City
Malabon City
Negros Occidental
Isabela
San Jose
Valenzuela
Pasay
Cainta
Norzagaray
Albay
Mabalacat
Antipolo
General Mariano Alvarez
Marikina
Taytay
Pangasinan
Zambales
Santa Cruz
San Mateo
Iligan City
Silang
Olongapo City
Santa Maria
Leyte
Binangonan
Western Samar
Bacoor
Rodriguez
Lipa City
General Trias
Marilao
Bocaue
Diplo
Nueva Ecija
Navotas
Malolos City
Pateros
Cotabato
Baguio
Maramag
Cagayan (Cagayan De Oro Is Different)
Apayao
Benguet
Camarines Norte
Naga City
City Of Tagum
Bicol
Bohol
Paombong, Bulacan
Gingoog City
Bataan
Tacloban
San Juan
Urdaneta
San Jose Del Monte
Sorsogon
Los Banos
Tuguegarao
City Of El Salvador
Malabon
Puerto Princesa
Caloocan City
Camiguin
Infanta Quezon
San Pedro
Guiguinto
Kalibo
Meycauyan
Masbate
Navotad
Kidapawan City
Misamis Oriental
Butuan
General Santos
Angono
Navotas City
Lopez, Quezon
Nueva Vizcaya
Oroquieta City
Amman
Dumaguete
Kidapawan
Ilocos Norte
Legazpi
Lucena City
Aurora
Bago City
Dolores
Lopez
Quirino
Dipolog
Valencia City
Santa Rosa
Carmona
Bay
Davao De Oro
Tuguegarao City
Tagum City
Cairo
Cape Town
Virac
Marinduque
Mauban
Bago
Alexandria
Tagoloan, Misamis Oriental
Angeles
Kinshasa
Capiz
South Korea
Kawit
Aklan
Cabadbaran City
Bambang
Lipa
Meycauayan
Catanduanes
Lopez, Quezon Province
Cadiz City
Antique
Marantao
Quezon Province
Mapandan
Ibajay
Accra
Daet, Camarines Norte
Romblon
Tayabas City

city_non_ph

Not Applicable
Newcastle
London
Prefer Not To Say
Oslo
Douala
Dammam
Phnom Penh
Bangkok
Diplo
Non
Uae
Tuguegarao City, Cagayan
Dasmarinas City, Cavite
Gen Mariano Alvarez
Ho Chi Minh
I Live In The Philippines
Perth
Navotas
Kansas
Dubai
Lagos State
Amman
Regina
Calamba
Philippines
Singapore
Benin City
Abu Dhabi, United Arab Emirates
Cairo
Ksa
Cape Town
Kathmandu
Soroti City Uganda
San Ildefonso
Alexandria
Sydney
Kinshasa
Cheongju City
Kuala Lumpur
Barishal
Sana'A
Jeddah
Ughelli
Pasco
Riyadh
Cerro De Pasco
Accra
Doha
Lagos

gender

Male
Female
LGBTQ+
Prefer not to say

educstat

Bachelor's or College Degree
Master's degree
Technical / Vocational
Associate degree
High school graduate
Prefer not to say
Doctorate / PhD
None of the above

have_comp_degree

No computer-related or data-related degree
Yes, I have a computer-related or data-related degree

comp_related_degree

Not Applicable
BS Electronics and Communications Engineering
BS Applied Mathematics or Related
BS Information Technology
BS Computer Engineering
BS Computer Science
BS Petroleum Engineering
MSc Data Science
BS Applied Statistics or Related
BS Mechatronics Engineering
Diploma in Information Technology
BA Business Economics
BS Accounting Information System
BS Data Science
BS Information Systems
Not applicable
BS Industrial Engineering
BS Civil Engineering
Bs Applied physixs
BS Applied Physics
Industrial Engineering
BS Applied Economics
BS Electrical Engineering Major in Computer Engineering
BS Economics
BS Statistics
MS Physics
BS Multimedia Arts
M.S. in Physics
Aeronautical Engineering
MS level
Associate Computer Science
BS Business Analytics
Association in computer technology
Information Technology
BSBA- Computer Applications
BS Accountancy
BS Physics
Two year course in computer programming
BS in Industrial Engineering
MS Data Science
MS Physics, and currently taking PhD Data Science
BS Agricultural and Biosystems Engineering
BS DATA SCIENCE AND ANALYTICS
Associate Degree in Computer Science
I attended SAP Abap Programming
Bachelor in Secondary Education
BSBA Banking and Finance
B Library and Information Science
BS Mathematics with Specialization in Computer Science
MS Computer Science
MBA in Cybersecurity
BSED - Technology and Livelihood Education
BS Agricultural and Applied Economics
BS Physics / MS Physics
BSBA Major in Computer Management
BET Computer Engineering Technology
Still on my 4th year BSIT
Pursuing my BSIT-Major in Data Analytics
Network telecommunication and technology
BET-Computer Engineering Technology
AB Psychology
BS Data Analytics
Bs statistics
Business Administration
Masters in Logistics Management
Postgraduate Diploma in data analysis
Data Analytics
BS Computer Applications
BSBA Major in Banking and Finance
Management Information Systems (MIS)
BS in Applied Mathematics and Data Science Track
Electrical Engineering
Business Administration Major in Marketing and Entrepreneurship
BS Chemistry
Currently taking up BS Computer Science
BS In Statistics
BS Mathematics major in Computer Science
BS Astronomy Major in Space Tech
BS Astronomy Major in Meteorological Sciences
BS Geodetic Engineering
CCNA and CCNP networking
Associate computer electronics technology
Bachelor of Science in Business Admin Major in Management Information System
Computer Technology
PGD Computer Science and Information Technology
BS Electrical Engineering Technology
Information Systems
BS Electronics Engineering, MS Applied Mathematical Sciences
BS Applied Mathematics
BS Cybersecurity
BS Mathematics
Post-Baccalaureate Degree in Information Technology
BS Chemical Engineering
BS Biology
BS Applied Physics with Computer Science Emphasis

careerstg

Career shifter - currently working in a non-data-related role
Professional - employed full-time in a data-related role
Student - currently studying and not yet working in a data-related role
Volunteer - contributing to data-related work without pay
Looking for data-related work - actively seeking opportunities
Government - employed in a data-related role in the public sector
Freelance - working independently in a data-related role

employertype

Local employer
Multinational employer
Foreign employer
Not Applicable
I'm self-employed
Public service
None of the above
I'm an entrepreneur

industry

Manpower Agency
It, Bpo, And Business Services
Banking / Finance / Insurance
Electric Utility
Fintech
Dating App
Not Applicable
Construction And Civil Engineering
Education
Recruitment Firm
None Of The Above
Telecommunication
Government
E-Commerce
Advertising
Electronics
Contractor Services
Accounting
Self-Employed
Engineering Consultancy
Media
Casino
Healthcare
Retail
Automation
Research
Ngo
Energy
Systems Integrators
Manufacturing
Career Shifter (Unspecified)
Engineering
Agriculture
Real Estate
Logistics And Delivery Services
Procurement
Own Business/ Consultancy/Freelance
Mining
Logistics
Transportation Services
It And Education
Technology And Real Estate
Utility
Fitness Tech
Biotechnology
Tourism
Logistics Supply Chain
Shipping
Gaming
Instrumentation And Control
Facility Management
Industrial Automation
Process Control Systems

salary

15,001 to 25,000
25,001 to 35,000
125,001 to 250,000
35,001 to 45,000
250,001 and above
Not Applicable
45,001 to 55,000
55,001 to 65,000
100,001 to 125,000
95,001 to 100,000
65,001 to 75,000
15,000 and below
75,001 to 85,000
85,001 to 95,000

how_long_in_salary

3 months or less
More than 2 years to 5 years
More than 1 year to 2 years
More than 5 years to 10 years
Not Applicable
More than 3 to 6 months
More than 6 months less than 1 year
More than 10 years
None of the above

typework

Contract fixed timeline
Full-time
Not Applicable
Freelance
None of the above
Part-time
Internship

sitework

Hybrid
Mostly onsite
Mostly work from home/ fully remote
Not Applicable
None of the above

shift_schedule

Day shift
Mid shift
Flexible
Not Applicable
Night shift

datarole

None Of The Above
Data Analysis & Insights
Data Engineering
Not Applicable
Data Science
Education & Learning
Technical Support & It Operations
Software Engineering
Research
Management & Leadership
Engineering
Admin & Support Role
Customer Service & Operations
Data Processing & Entry
Legal & Public Affairs
Marketing & Sales
Content Related
Consulting & Freelance

side_gig

I did NOT have side gigs in the past 12 months
Not Applicable
I HAD at least one side gig in the past 12 months

satisfaction

4.0
6.0
10.0
999.0
7.0
9.0
8.0
3.0
5.0
2.0
1.0

sizeteam

Not applicable
4 to 5
30+
6 to 10
11 to 30
Not Applicable
2 to 3
1 - Just me

ai_work

Yes, I use AI tools DAILY for work.
Yes, I use AI tools WEEKLY for work.
No, but I plan to soon.
None of the above
Yes, I use AI tools MONTHLY or LESS frequently for work.
No, and I don't plan to.

ai_study

Yes, I use AI tools DAILY for study.
Yes, I use AI tools WEEKLY for study
No, but I plan to soon.
None of the above
Yes, I use AI tools MONTHLY or LESS frequently for study.
No, and I don't plan to.


Date and Time:  2026-03-09 16:47:20

In [ ]:
# 4b. Convert unique values to starter csv files for lookup and store in unique_dir 
# -> copy and edit into lookup_dir as final lookup csv 
# -> unique_dir -> lookup_dir after manual transformation

single_columns_non_numeric = [
    col for col in df_single_no_grps.columns
    if col not in ["resp_id", "age", "resp_id_rand", "satisfaction"]
]

for col in single_columns_non_numeric:
    uniques = (
        df_single_no_grps[col]
        .dropna()
        .astype(str)
        .unique()
    )
    uniques_sorted = sorted(uniques)

    out_df = pd.DataFrame({"raw": uniques_sorted})
    out_path = unique_dir / f"{col}.csv"
    out_df.to_csv(out_path, index=False, encoding="utf-8")

print("~"*80)
print("Per-column unique CSVs created in unique_dir.")
print("Date and Time: ", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Per-column unique CSVs created in unique_dir.
Date and Time:  2026-03-09 16:47:38

In [55]:
# 4c. Create temp lookup csv files (staging column) in lookup_dir using the raw column values as clean_temp
# Three types of edits: 1. no edits (direct clean), 2. special edits, 3. manual edits (the rest)

# List of no edit files - type 1
direct_clean_csv_files = ["ai_study_lookup.csv", "ai_work_lookup.csv", "careerstg_lookup.csv", "datarole_lookup.csv", "educstat_lookup.csv", "employertype_lookup.csv", "gender_lookup.csv", "industry_lookup.csv","satisfaction_lookup.csv", "shift_schedule_lookup.csv","sitework_lookup.csv","sizeteam_lookup.csv", "typework_lookup.csv"]

# List of special edit files - type 2
specific_csv_lookup_files = ["have_comp_degree_lookup.csv", "side_gig_lookup.csv", "salary_lookup.csv", "how_long_in_salary_lookup.csv"]

# Create temp lookup csv files in lookup_dir
for file in unique_dir.glob("*.csv"):
    df = pd.read_csv(file, dtype=str)
    
    # Copy the raw column to "clean_temp" staging column
    df["clean_temp"] = df["raw"]
    
    # Generate the target filename as lookup
    lookup_filename = f"{file.stem}_lookup.csv"
    
    # Directly convert "clean_temp" to "clean" for direct clean →  Type 1 edit
    if lookup_filename in direct_clean_csv_files:
        # Renaming the column to 'clean' for matches
        df.rename(columns={"clean_temp": "clean"}, inplace=True)

    # Exporting the file to the output directory
    out_path = lookup_dir / lookup_filename
    df.to_csv(out_path, index=False, encoding="utf-8")
    print(f"Created: {out_path}")

Created: lookup_dir\ai_study_lookup.csv
Created: lookup_dir\ai_work_lookup.csv
Created: lookup_dir\careerstg_lookup.csv
Created: lookup_dir\city_non_ph_lookup.csv
Created: lookup_dir\city_ph_lookup.csv
Created: lookup_dir\comp_related_degree_lookup.csv
Created: lookup_dir\country_lookup.csv
Created: lookup_dir\datarole_lookup.csv
Created: lookup_dir\educstat_lookup.csv
Created: lookup_dir\employertype_lookup.csv
Created: lookup_dir\gender_lookup.csv
Created: lookup_dir\have_comp_degree_lookup.csv
Created: lookup_dir\how_long_in_salary_lookup.csv
Created: lookup_dir\industry_lookup.csv
Created: lookup_dir\salary_lookup.csv
Created: lookup_dir\satisfaction_lookup.csv
Created: lookup_dir\shift_schedule_lookup.csv
Created: lookup_dir\side_gig_lookup.csv
Created: lookup_dir\sitework_lookup.csv
Created: lookup_dir\sizeteam_lookup.csv
Created: lookup_dir\typework_lookup.csv

In [56]:
# 4d. Special lookup files given different wording vs. labels for charts
# have_comp_degree, side_gig, salary, how_long_in_salary
# Create map → apply map function & drop temp → export

import pandas as pd


# Define all maps → feeds into dictionary → replace "clean_temp" in lookup
map_comp_degree = {
    "No computer-related or data-related degree": "Not have",
    "Yes, I have a computer-related or data-related degree": "Have comp or data degree"
}

map_side_gig = {
    "I HAD at least one side gig in the past 12 months": "Side gig p12m",
    "I did NOT have side gigs in the past 12 months": "No side gig p12m"
}

map_salary = {
    "100,001 to 125,000":"100k+ to 125k",
    "125,001 to 250,000":"125k+ to 250k",
    "15,000 and below":"15k and below",
    "15,001 to 25,000":"15k+ to 25k",
    "25,001 to 35,000":"25k+ to 35k",
    "250,001 and above":"250k and above",
    "35,001 to 45,000":"35k+ to 45k",
    "45,001 to 55,000":"45k+ to 55k",
    "55,001 to 65,000":"55k+ to 65k",
    "65,001 to 75,000":"65k+ to 75k",
    "75,001 to 85,000":"75k+ to 85k",
    "85,001 to 95,000":"85k+ to 95k",
    "95,001 to 100,000":"95k+ to 100k"
}

map_salary_duration = {
    "3 months or less": "a. 3mos or less",
    "More than 3 to 6 months": "b. >3 to 6mos",
    "More than 6 months less than 1 year": "c. >6mos to 1yr",
    "More than 1 year to 2 years": "d. >1yr to 2yrs",
    "More than 2 years to 5 years": "e. >2 yrs to 5yrs",
    "More than 5 years to 10 years": "f. >5 yrs to 10yrs",
    "More than 10 years": "g. >10yrs",
    "None of the above": "h. Not Applicable",
    "Not Applicable": "Not Applicable"
}

# Dictionary for all special mappings 
all_mappings = {
    "have_comp_degree": map_comp_degree,
    "side_gig": map_side_gig,
    "salary": map_salary,
    "how_long_in_salary": map_salary_duration
}

# Function apply_special_map → lookup files
def apply_special_map(col_name, mapping_dict, lookup_dir):
    """
    Same method, different mappings. Reads, maps, cleans, and exports lookup CSVs.
    Uses 'clean_temp' as the common source column.
    """
    file_path = lookup_dir / f"{col_name}_lookup.csv"
    df = pd.read_csv(file_path, dtype=str)    
    df["clean"] = df["clean_temp"].map(mapping_dict).fillna(df["clean_temp"])
    
    # Remove the staging column and overwrite the source file
    df.drop(columns=["clean_temp"], inplace=True)
    df.to_csv(file_path, index=False)

# Apply function to special columns
for col, mapping in all_mappings.items():
    apply_special_map(col, mapping, lookup_dir)

In [ ]:
# 4d. Identify files to manually edit → Type 3 edit

# This is unavoidable. Some columns really need human input.  Attempt to use AI resulted in missed important items (ex. BS Business Administration ← failed to convert to  BSBA Major Unspecified, Two year computer course ← failed to convert to Associate, and more)

# Initialize {set} object to contain all file names in lookup dir using file paths
all_files_in_lookup_dir_set = {f"{file.stem}_lookup.csv" for file in unique_dir.glob("*.csv")}

# Subtract direct clean csv files and special csv lookup files.
# Use the set difference to remove the clean files
manual_edit_lookup_files = sorted(list(all_files_in_lookup_dir_set - set(direct_clean_csv_files) - set(specific_csv_lookup_files)))

print("Files to manually edit:")
print(manual_edit_lookup_files)
print("REMOVE ALL COMMAS AND NON LETTER CHARACTERS, OPTIONS THAT CAN BE CONVERGED TO ONE, WRONG GRAMMAR")
print("AND THEN COPY AND PASTE INTO THE CORRECT FILENAME IN THE MANUAL_EDIT FOLDER")

Files to manually edit:
['city_non_ph_lookup.csv', 'city_ph_lookup.csv', 'comp_related_degree_lookup.csv', 'country_lookup.csv']
REMOVE ALL COMMAS AND NON LETTER CHARACTERS, OPTIONS THAT CAN BE CONVERGED TO ONE, WRONG GRAMMAR
AND THEN COPY AND PASTE INTO THE CORRECT FILENAME IN THE MANUAL_EDIT FOLDER

## REMINDER: COPY AND PASTE MANUAL EDIT LOOKUP FILES IN A MANUAL_EDIT SUBFOLDER NOW.

In [59]:
# Lookup files -- Add Not Applicable to both raw and clean columns if not yet present
from pathlib import Path
import pandas as pd

# Define the directory containing your data files
lookup_dir = Path("lookup_dir")

for file in lookup_dir.glob("*.csv"):
    # Load the data into a structured table format
    # We use 'latin-1' to ensure compatibility with various data sources
    df = pd.read_csv(file, dtype=str, keep_default_na=False, encoding="latin-1")

    # Verify that the necessary 'raw' and 'clean' categories exist
    for col in ("raw", "clean"):
        if col not in df.columns:
            df[col] = ""

    # Check if the specific 'Not Applicable' pair already exists in the data
    na_exists = ((df["raw"] == "Not Applicable") & (df["clean"] == "Not Applicable")).any()

    # Append the row only if it is missing from the current records
    if not na_exists:
        df.loc[len(df)] = {"raw": "Not Applicable", "clean": "Not Applicable"}

        # Overwrite the file with the updated information in a standardized format
        df.to_csv(file, index=False, encoding="utf-8")
        print(f"Successfully updated: {file.name}")

In [ ]:
# 5. Now apply the lookups (Single-Response Columns)
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# At this point, lookups are already created in lookup_dir and manually revised.
# df_raw is still unchanged at this point. A new df_single_no_grps is created below.
# Create apply_lookup function using df and column
# Apply the created lookups and print unmatched items

single_cols_no_grps = [
    "resp_id", "country", "city_ph", "city_non_ph", "gender", "age", "educstat", "have_comp_degree", "comp_related_degree", "careerstg", "employertype", "industry", "salary", "how_long_in_salary", "typework", "sitework", "shift_schedule", "datarole", "side_gig", "satisfaction", "sizeteam", "ai_work", "ai_study", "resp_id_rand"
]
df_raw = pd.read_parquet("parquet_outputs_dir/df_raw.parquet")
df_single_no_grps = df_raw[single_cols_no_grps].copy()

# Export before lookup
df_single_no_grps.to_csv(csv_outputs_dir/"df_single_no_grps_before_lookup.csv", index=False)  

# Re-run the single_column_non_numerics definition
single_columns_non_numeric = [
    col for col in df_single_no_grps.columns
    if col not in ["resp_id", "age", "resp_id_rand", "satisfaction"]
]

In [ ]:
# 5a. Apply lookup function to single - response columns
# Create check unique values in df_single_no_grps and apply lookup
# → apply_lookup function → convert df_single_no_grps.csv using lookup
def apply_lookup(df, column):
    lookup_file = lookup_dir / f"{column}_lookup.csv"
    if not lookup_file.exists():
        print(f"{column} lookup file not found.")
        return df

    map_df = pd.read_csv(lookup_file, encoding="windows-1252", quotechar='"', quoting=csv.QUOTE_MINIMAL, dtype=str, keep_default_na=False)
    map_df["raw"] = map_df["raw"].fillna("")
    map_df["clean"] = map_df["clean"].fillna("")

    list_raw = list(df[column].unique())
    list_lookup = list(map_df["raw"].unique())

    unmatched = [x for x in list_raw if x not in list_lookup]
    if not unmatched:
        print (f"All items in {column} are matched.")
    else:
        print(f"Unmatched items in {column}:")
        for item in unmatched:
            print(repr(item))  # official string representation

    mapping = dict(zip(map_df["raw"], map_df["clean"]))

    df[column] = df[column].map(mapping).fillna("Not Applicable")
    return df


for col in single_columns_non_numeric:
    df_single_no_grps= apply_lookup(df_single_no_grps, col)
    print("~"*20)

# Logging...
import datetime
print('Run date: ', datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
# Update the df_single_no_grps csv file
df_single_no_grps.to_csv(csv_outputs_dir/ "df_single_no_grps_after_lookup.csv", index = False)

All items in country are matched.
~~~~~~~~~~~~~~~~~~~~
All items in city_ph are matched.
~~~~~~~~~~~~~~~~~~~~
All items in city_non_ph are matched.
~~~~~~~~~~~~~~~~~~~~
All items in gender are matched.
~~~~~~~~~~~~~~~~~~~~
All items in educstat are matched.
~~~~~~~~~~~~~~~~~~~~
All items in have_comp_degree are matched.
~~~~~~~~~~~~~~~~~~~~
All items in comp_related_degree are matched.
~~~~~~~~~~~~~~~~~~~~
All items in careerstg are matched.
~~~~~~~~~~~~~~~~~~~~
All items in employertype are matched.
~~~~~~~~~~~~~~~~~~~~
All items in industry are matched.
~~~~~~~~~~~~~~~~~~~~
All items in salary are matched.
~~~~~~~~~~~~~~~~~~~~
All items in how_long_in_salary are matched.
~~~~~~~~~~~~~~~~~~~~
All items in typework are matched.
~~~~~~~~~~~~~~~~~~~~
All items in sitework are matched.
~~~~~~~~~~~~~~~~~~~~
All items in shift_schedule are matched.
~~~~~~~~~~~~~~~~~~~~
All items in datarole are matched.
~~~~~~~~~~~~~~~~~~~~
All items in side_gig are matched.
~~~~~~~~~~~~~~~~~~~~
All items in sizeteam are matched.
~~~~~~~~~~~~~~~~~~~~
All items in ai_work are matched.
~~~~~~~~~~~~~~~~~~~~
All items in ai_study are matched.
~~~~~~~~~~~~~~~~~~~~
Run date:  2026-03-09 17:41:28

# Stop here.  Inspect unmatched items.  Manually edit lookup files if needed.
- No need to run lookup again - second pre-cleaning.
- At this point, df_single_no_grps values are already updated, so cannot re-run item 5. Lookups. 
- If you need to run the subset:
    - Just edit the lookups manually in VSCode, not Excel.
    - Or define the subset, noting that artificial unmatched items will appear.

# 5a.1. Re-run lookups only for subset based on the output above to minimize artificial mismatch items. (Optional)
# Do not re-run cell #5a because some df_raw columns are already standardized and replaced.
# So some 'unmatched' items are artificial because the df_single_no_grps raw column is already transformed to clean column.  
# This list of subset columns to re-run was the result of the first pre-cleaning.
# Second pre-cleaning did not have any unmatched items anymore.

subset_rerun = ['city_non_ph', 'comp_related_degree', 'employertype', 'industry', 'salary', 'how_long_in_salary', 'typework', 'sitework', 'shift_schedule', 'datarole', 'side_gig', 'satisfaction', 'sizeteam']

df_single_no_grps[subset_rerun] = df_single_no_grps[subset_rerun].fillna("Not Applicable")

for col in subset_rerun:
    df_single_no_grps= apply_lookup(df_single_no_grps, col)
    print(f"\n{col} lookup done.\n")
    print("~"*20)

print("Proceed to inspection again, next cell.")

In [66]:
# 5b. Inspect the updated df_single_no_grps unique values. (Optional)
# During pre-cleaning - this was only to check if unforeseen unmatched values still appeared.
def explore_categorical_cols(col, df):
    print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
    print(f'Exploration of {col} column')
    print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
     
    # Normal categorical branch
    unique_count = df[col].nunique()
    
    # Skip high-cardinality columns
    if unique_count > 100:
        print(f"Skipping {col} (unique values = {unique_count}, exceeds threshold of 100).")
        print()
        return
   
    print(f'Description of {col} ~~~~~~~~~~')
    print(df[col].describe())
    print()
    print(f'Value counts of {col} ~~~~~~~~~~')
    print(df[col].value_counts(dropna=False))
    print()

single_cols_no_grps
# Loop through categorical columns
for col in single_cols_no_grps:
    explore_categorical_cols(col, df_single_no_grps)

print ("At this point, all unique items should be clean.")
print ("Still no age_grp because we need exact age for the duplication check.")
print ("Date and Time: ", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exploration of resp_id column
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Skipping resp_id (unique values = 1732, exceeds threshold of 100).

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exploration of country column
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Description of country ~~~~~~~~~~
count            1732
unique             30
top       Philippines
freq             1679
Name: country, dtype: object

Value counts of country ~~~~~~~~~~
country
Philippines             1679
Nigeria                    7
Egypt                      6
United Arab Emirates       4
United Kingdom             3
Canada                     3
Saudi Arabia               3
Uganda                     2
United States              2
Nepal                      2
Peru                       2
Cambodia                   1
Cameroon                   1
Norway                     1
Jordan                     1
Uae                        1
Pakistan                   1
Thailand                   1
Congo                      1
South Korea                1
Malaysia                   1
South Africa               1
Bangladesh                 1
Yemen                      1
Kenya                      1
Algeria                    1
Vietnam                    1
Ghana                      1
India                      1
Spain                      1
Name: count, dtype: int64

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exploration of city_ph column
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Skipping city_ph (unique values = 174, exceeds threshold of 100).

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exploration of city_non_ph column
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Description of city_non_ph ~~~~~~~~~~
count               1732
unique                42
top       Not Applicable
freq                1660
Name: city_non_ph, dtype: object

Value counts of city_non_ph ~~~~~~~~~~
city_non_ph
Not Applicable        1660
Prefer Not To Say       21
Cairo                    4
Dubai                    3
Sydney                   2
Alexandria               2
Ho Chi Minh              2
Lagos                    2
Regina                   2
Calamba                  2
Diplo                    1
Bangkok                  1
Phnom Penh               1
Dammam                   1
Douala                   1
Oslo                     1
London                   1
Newcastle                1
Amman                    1
UAE                      1
Benin City               1
Singapore                1
Abu Dhabi                1
KSA                      1
Kansas                   1
Perth                    1
Kathmandu                1
Cape Town                1
San Ildefonso            1
Soroti City Uganda       1
Kinshasa                 1
Cheongju City            1
Kuala Lumpur             1
Barishal                 1
Sana'A                   1
Jeddah                   1
Ughelli                  1
Pasco                    1
Riyadh                   1
Cerro De Pasco           1
Accra                    1
Doha                     1
Name: count, dtype: int64

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exploration of gender column
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Description of gender ~~~~~~~~~~
count     1732
unique       4
top       Male
freq      1146
Name: gender, dtype: object

Value counts of gender ~~~~~~~~~~
gender
Male                 1146
Female                487
LGBTQ+                 71
Prefer not to say      28
Name: count, dtype: int64

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exploration of age column
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Description of age ~~~~~~~~~~
count    1732.000000
mean       26.686490
std         6.251459
min        16.000000
25%        22.000000
50%        25.000000
75%        30.000000
max        66.000000
Name: age, dtype: float64

Value counts of age ~~~~~~~~~~
age
23    187
22    174
21    160
25    152
24    128
28    102
26     99
27     89
30     79
29     73
20     69
31     59
32     47
34     35
33     35
19     34
35     32
18     25
36     23
38     19
37     16
40     15
39     13
44      9
42      9
45      6
47      5
48      5
46      5
43      4
41      4
52      3
49      3
54      3
17      3
58      2
51      1
66      1
60      1
50      1
16      1
57      1
Name: count, dtype: int64

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exploration of educstat column
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Description of educstat ~~~~~~~~~~
count                             1732
unique                               8
top       Bachelor's or College Degree
freq                              1366
Name: educstat, dtype: object

Value counts of educstat ~~~~~~~~~~
educstat
Bachelor's or College Degree    1366
High school graduate             196
Master's degree                   85
Associate degree                  36
Prefer not to say                 17
Technical / Vocational            14
None of the above                 11
Doctorate / PhD                    7
Name: count, dtype: int64

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exploration of have_comp_degree column
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Description of have_comp_degree ~~~~~~~~~~
count                         1732
unique                           2
top       Have comp or data degree
freq                          1095
Name: have_comp_degree, dtype: object

Value counts of have_comp_degree ~~~~~~~~~~
have_comp_degree
Have comp or data degree    1095
Not have                     637
Name: count, dtype: int64

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exploration of comp_related_degree column
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Description of comp_related_degree ~~~~~~~~~~
count               1732
unique                84
top       Not Applicable
freq                 616
Name: comp_related_degree, dtype: object

Value counts of comp_related_degree ~~~~~~~~~~
comp_related_degree
Not Applicable                                         616
BS Computer Science                                    302
BS Information Technology                              253
BS Computer Engineering                                162
BS Electronics and Communications Engineering          126
                                                      ...
BS Cybersecurity                                         1
Post Baccalaureate Degree in Information Technology      1
BS Chemical Engineering                                  1
BS Biology                                               1
BS Applied Physics with Computer Science Emphasis        1
Name: count, Length: 84, dtype: int64

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exploration of careerstg column
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Description of careerstg ~~~~~~~~~~
count                                                  1732
unique                                                    7
top       Student - currently studying and not yet worki...
freq                                                    581
Name: careerstg, dtype: object

Value counts of careerstg ~~~~~~~~~~
careerstg
Student - currently studying and not yet working in a data-related role    581
Looking for data-related work - actively seeking opportunities             371
Professional - employed full-time in a data-related role                   353
Career shifter - currently working in a non-data-related role              322
Freelance - working independently in a data-related role                    50
Government - employed in a data-related role in the public sector           38
Volunteer - contributing to data-related work without pay                   17
Name: count, dtype: int64

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exploration of employertype column
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Description of employertype ~~~~~~~~~~
count               1732
unique                 8
top       Not Applicable
freq                 969
Name: employertype, dtype: object

Value counts of employertype ~~~~~~~~~~
employertype
Not Applicable            969
Local employer            267
Multinational employer    203
Foreign employer          163
Public service             53
None of the above          39
I'm self-employed          34
I'm an entrepreneur         4
Name: count, dtype: int64

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exploration of industry column
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Description of industry ~~~~~~~~~~
count               1732
unique                53
top       Not Applicable
freq                 969
Name: industry, dtype: object

Value counts of industry ~~~~~~~~~~
industry
Not Applicable                         969
It, Bpo, And Business Services         202
Banking / Finance / Insurance           75
None Of The Above                       58
Government                              35
Healthcare                              30
Manufacturing                           29
Education                               25
Fintech                                 23
E-Commerce                              22
Accounting                              20
Engineering                             19
Construction And Civil Engineering      18
Career Shifter (Unspecified)            18
It And Education                        17
Research                                16
Telecommunication                       12
Advertising                             12
Retail                                  11
Energy                                   9
Real Estate                              8
Self-Employed                            7
Agriculture                              6
Casino                                   6
Media                                    6
Manpower Agency                          6
Contractor Services                      5
Ngo                                      5
Electric Utility                         4
Transportation Services                  4
Procurement                              4
Logistics                                4
Automation                               4
Systems Integrators                      4
Engineering Consultancy                  3
Recruitment Firm                         3
Electronics                              3
Logistics Supply Chain                   3
Logistics And Delivery Services          3
Technology And Real Estate               3
Mining                                   3
Tourism                                  3
Dating App                               2
Own Business/ Consultancy/Freelance      2
Utility                                  2
Biotechnology                            2
Fitness Tech                             1
Shipping                                 1
Gaming                                   1
Instrumentation And Control              1
Facility Management                      1
Industrial Automation                    1
Process Control Systems                  1
Name: count, dtype: int64

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exploration of salary column
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Description of salary ~~~~~~~~~~
count               1732
unique                14
top       Not Applicable
freq                 969
Name: salary, dtype: object

Value counts of salary ~~~~~~~~~~
salary
Not Applicable    969
25k+ to 35k       149
15k+ to 25k       138
35k+ to 45k        97
15k and below      72
45k+ to 55k        70
125k+ to 250k      50
65k+ to 75k        42
55k+ to 65k        41
100k+ to 125k      37
75k+ to 85k        18
95k+ to 100k       17
250k and above     16
85k+ to 95k        16
Name: count, dtype: int64

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exploration of how_long_in_salary column
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Description of how_long_in_salary ~~~~~~~~~~
count               1732
unique                 9
top       Not Applicable
freq                 969
Name: how_long_in_salary, dtype: object

Value counts of how_long_in_salary ~~~~~~~~~~
how_long_in_salary
Not Applicable        969
d. >1yr to 2yrs       202
e. >2 yrs to 5yrs     142
c. >6mos to 1yr       131
a. 3mos or less       124
b. >3 to 6mos          97
f. >5 yrs to 10yrs     34
h. Not Applicable      23
g. >10yrs              10
Name: count, dtype: int64

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exploration of typework column
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Description of typework ~~~~~~~~~~
count               1732
unique                 7
top       Not Applicable
freq                 969
Name: typework, dtype: object

Value counts of typework ~~~~~~~~~~
typework
Not Applicable             969
Full-time                  602
Contract fixed timeline     55
Freelance                   50
None of the above           32
Part-time                   22
Internship                   2
Name: count, dtype: int64

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exploration of sitework column
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Description of sitework ~~~~~~~~~~
count               1732
unique                 5
top       Not Applicable
freq                 969
Name: sitework, dtype: object

Value counts of sitework ~~~~~~~~~~
sitework
Not Applicable                         969
Mostly onsite                          269
Mostly work from home/ fully remote    241
Hybrid                                 222
None of the above                       31
Name: count, dtype: int64

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exploration of shift_schedule column
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Description of shift_schedule ~~~~~~~~~~
count               1732
unique                 5
top       Not Applicable
freq                1032
Name: shift_schedule, dtype: object

Value counts of shift_schedule ~~~~~~~~~~
shift_schedule
Not Applicable    1032
Day shift          402
Night shift        122
Flexible            98
Mid shift           78
Name: count, dtype: int64

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exploration of datarole column
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Description of datarole ~~~~~~~~~~
count               1732
unique                18
top       Not Applicable
freq                 999
Name: datarole, dtype: object

Value counts of datarole ~~~~~~~~~~
datarole
Not Applicable                       999
Data Analysis & Insights             199
Admin & Support Role                  83
Data Engineering                      80
Software Engineering                  56
Technical Support & It Operations     51
Customer Service & Operations         47
Engineering                           45
Data Processing & Entry               39
None Of The Above                     33
Education & Learning                  22
Management & Leadership               19
Research                              17
Data Science                          13
Marketing & Sales                     13
Consulting & Freelance                11
Content Related                        3
Legal & Public Affairs                 2
Name: count, dtype: int64

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exploration of side_gig column
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Description of side_gig ~~~~~~~~~~
count               1732
unique                 3
top       Not Applicable
freq                 969
Name: side_gig, dtype: object

Value counts of side_gig ~~~~~~~~~~
side_gig
Not Applicable      969
No side gig p12m    594
Side gig p12m       169
Name: count, dtype: int64

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exploration of satisfaction column
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Description of satisfaction ~~~~~~~~~~
count    1732.000000
mean      561.575058
std       493.095460
min         1.000000
25%         7.000000
50%       999.000000
75%       999.000000
max       999.000000
Name: satisfaction, dtype: float64

Value counts of satisfaction ~~~~~~~~~~
satisfaction
999.0    969
8.0      131
7.0      126
5.0      116
6.0       99
1.0       62
10.0      62
4.0       57
9.0       50
3.0       33
2.0       27
Name: count, dtype: int64

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exploration of sizeteam column
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Description of sizeteam ~~~~~~~~~~
count               1732
unique                 8
top       Not Applicable
freq                 969
Name: sizeteam, dtype: object

Value counts of sizeteam ~~~~~~~~~~
sizeteam
Not Applicable    969
Not applicable    223
1 - Just me       126
2 to 3            108
6 to 10            93
4 to 5             85
11 to 30           72
30+                56
Name: count, dtype: int64

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exploration of ai_work column
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Description of ai_work ~~~~~~~~~~
count                                    1732
unique                                      6
top       Yes, I use AI tools DAILY for work.
freq                                      881
Name: ai_work, dtype: object

Value counts of ai_work ~~~~~~~~~~
ai_work
Yes, I use AI tools DAILY for work.                         881
Yes, I use AI tools WEEKLY for work.                        287
No, but I plan to soon.                                     217
None of the above                                           166
Yes, I use AI tools MONTHLY or LESS frequently for work.    157
No, and I don't plan to.                                     24
Name: count, dtype: int64

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exploration of ai_study column
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Description of ai_study ~~~~~~~~~~
count                                     1732
unique                                       6
top       Yes, I use AI tools DAILY for study.
freq                                      1006
Name: ai_study, dtype: object

Value counts of ai_study ~~~~~~~~~~
ai_study
Yes, I use AI tools DAILY for study.                         1006
Yes, I use AI tools WEEKLY for study                          370
Yes, I use AI tools MONTHLY or LESS frequently for study.     186
No, but I plan to soon.                                       112
None of the above                                              31
No, and I don't plan to.                                       27
Name: count, dtype: int64

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Exploration of resp_id_rand column
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Skipping resp_id_rand (unique values = 1732, exceeds threshold of 100).

At this point, all unique items should be clean.
Still no age_grp because we need exact age for the duplication check.
Date and Time:  2026-03-09 18:14:32

# Check similarity - single response columns

In [62]:
# 5c. Check similarity - preliminary duplicate checks among single-response columns first
# Set up the cleaned single‑response dataframe that we will compare
df_sim_raw = df_single_no_grps.copy()

# List the columns we will use to score similarity
compare_cols = [
    "country", "city_ph", "city_non_ph", "gender", "age", "educstat",
    "have_comp_degree", "comp_related_degree", "careerstg", "employertype",
    "industry", "salary", "how_long_in_salary", "typework", "sitework",
    "shift_schedule", "datarole", "side_gig", "satisfaction", "sizeteam",
    "ai_work", "ai_study"
]

# Initialize list to hold the similarity results for each respondent
results = []

# Loop through each respondent one at a time
for idx, row in df_sim_raw.iterrows():

    # Create a row‑vs‑all‑rows comparison so we can see who looks similar
    # Compare is the boolean dataframe that contains results True/False per column
    compare = df_sim_raw[compare_cols] == row[compare_cols]

    # Count how many fields match for each respondent
    match_counts = compare.sum(axis=1)

    # Remove the self‑match so it doesn't interfere with scoring
    match_counts.loc[idx] = -1

    # Get the highest match score for this respondent
    max_score = match_counts.max()

    # Grab all respondents who hit that same top score
    best_idxs = match_counts[match_counts == max_score].index.tolist()

    # Save the result so we can review or export later
    results.append({
        "resp_id": row["resp_id"],
        "best_match_resp_ids": df_sim_raw.loc[best_idxs, "resp_id"].tolist(),
        "best_score": int(max_score),
        "total": len(compare_cols),
        "similarity": max_score / len(compare_cols)
    })

# Turn the collected results into a dataframe
df_sim = pd.DataFrame(results)
df_sim

      resp_id              best_match_resp_ids  best_score  total  similarity
0           1                           [1373]          15     22    0.681818
1           2           [232, 420, 1413, 1445]          14     22    0.636364
2           3                            [402]          18     22    0.818182
3           4                            [222]          15     22    0.681818
4           5  [123, 125, 163, 385, 454, 1168]          14     22    0.636364
...       ...                              ...         ...    ...         ...
1727     1728                           [1727]          22     22    1.000000
1728     1729                            [977]          11     22    0.500000
1729     1730                            [951]          20     22    0.909091
1730     1731           [506, 955, 1451, 1674]          21     22    0.954545
1731     1732                     [1041, 1273]          21     22    0.954545

[1732 rows x 5 columns]

In [27]:
# 5d. Inspect the highest scores
df_sim_sorted = df_sim.sort_values(by = 'similarity', ascending = False)
print(df_sim_sorted[['resp_id', 'best_match_resp_ids', 'similarity']].head(50))
df_sim_sorted.to_csv(csv_outputs_dir/ "df_sim_sorted.csv", index = False)

     resp_id                    best_match_resp_ids  similarity
1726    1727                                 [1728]    1.000000
356      357                                  [101]    1.000000
470      471                                  [502]    1.000000
1573    1574                                 [1099]    1.000000
1627    1628                                 [1123]    1.000000
501      502                                  [471]    1.000000
342      343                                 [1382]    1.000000
576      577                                  [337]    1.000000
336      337                                  [577]    1.000000
591      592                                 [1120]    1.000000
704      705                                 [1081]    1.000000
305      306                                 [1031]    1.000000
780      781                                  [202]    1.000000
838      839                                 [1285]    1.000000
844      845                                 [1211]    1.000000
238      239                                 [1418]    1.000000
960      961                                 [1419]    1.000000
217      218                                 [1315]    1.000000
1533    1534                                 [1624]    1.000000
1030    1031                                  [306]    1.000000
194      195                                 [1189]    1.000000
197      198                                 [1337]    1.000000
201      202                                  [781]    1.000000
1080    1081                                  [705]    1.000000
1098    1099                                 [1574]    1.000000
1119    1120                                  [592]    1.000000
1122    1123                                 [1628]    1.000000
1188    1189                                  [195]    1.000000
1189    1190                                 [1338]    1.000000
1210    1211                                  [845]    1.000000
1284    1285                                  [839]    1.000000
1314    1315                                  [218]    1.000000
1336    1337                                  [198]    1.000000
1337    1338                                 [1190]    1.000000
1381    1382                                  [343]    1.000000
100      101                                  [357]    1.000000
1417    1418                                  [239]    1.000000
1418    1419                                  [961]    1.000000
1727    1728                                 [1727]    1.000000
1623    1624                                 [1534]    1.000000
22        23                         [44, 376, 804]    0.954545
376      377                        [84, 274, 1292]    0.954545
377      378              [84, 201, 255, 586, 1422]    0.954545
1692    1693                                 [1651]    0.954545
1718    1719                             [53, 1094]    0.954545
25        26                        [130, 297, 311]    0.954545
1691    1692                            [637, 1723]    0.954545
1683    1684                                  [614]    0.954545
1673    1674  [113, 217, 506, 900, 955, 1451, 1731]    0.954545
1671    1672                                 [1458]    0.954545

In [67]:
# 5e. Filter respondents most likely to be duplicates 
# Score == 1 & only one best_match_resp_ids using apply(len) == 1)
df_sim_sorted = df_sim.sort_values(by = 'similarity', ascending = False)
df_likely_dups = df_sim_sorted[
    (df_sim_sorted['best_match_resp_ids'].apply(len) == 1) &
    (df_sim_sorted['similarity'] == 1)
]

print(df_likely_dups.head(50))

# Export the df_likely_dups to csv outputs
df_likely_dups.to_csv(csv_outputs_dir/"df_likely_dups.csv", index = False)

      resp_id best_match_resp_ids  best_score  total  similarity
1726     1727              [1728]          22     22         1.0
356       357               [101]          22     22         1.0
470       471               [502]          22     22         1.0
1573     1574              [1099]          22     22         1.0
1627     1628              [1123]          22     22         1.0
501       502               [471]          22     22         1.0
342       343              [1382]          22     22         1.0
576       577               [337]          22     22         1.0
336       337               [577]          22     22         1.0
591       592              [1120]          22     22         1.0
704       705              [1081]          22     22         1.0
305       306              [1031]          22     22         1.0
780       781               [202]          22     22         1.0
838       839              [1285]          22     22         1.0
844       845              [1211]          22     22         1.0
238       239              [1418]          22     22         1.0
960       961              [1419]          22     22         1.0
217       218              [1315]          22     22         1.0
1533     1534              [1624]          22     22         1.0
1030     1031               [306]          22     22         1.0
194       195              [1189]          22     22         1.0
197       198              [1337]          22     22         1.0
201       202               [781]          22     22         1.0
1080     1081               [705]          22     22         1.0
1098     1099              [1574]          22     22         1.0
1119     1120               [592]          22     22         1.0
1122     1123              [1628]          22     22         1.0
1188     1189               [195]          22     22         1.0
1189     1190              [1338]          22     22         1.0
1210     1211               [845]          22     22         1.0
1284     1285               [839]          22     22         1.0
1314     1315               [218]          22     22         1.0
1336     1337               [198]          22     22         1.0
1337     1338              [1190]          22     22         1.0
1381     1382               [343]          22     22         1.0
100       101               [357]          22     22         1.0
1417     1418               [239]          22     22         1.0
1418     1419               [961]          22     22         1.0
1727     1728              [1727]          22     22         1.0
1623     1624              [1534]          22     22         1.0

In [ ]:
# 5f. Create df possible duplicates based on the single response columns.

df_possible_duplicates = pd.merge(df_single_no_grps, df_likely_dups, how = "inner", on = "resp_id")
df_possible_duplicates.to_csv(csv_outputs_dir/ "df_possible_duplicates.csv", index = False)
df_possible_duplicates

# 6. Create groups for age and salary

In [69]:
# 6a. Create age_grp in df_single_no_grps
# Initialize the df_single_with_grps

df_single_no_grps = pd.read_csv("csv_outputs_dir/df_single_no_grps_after_lookup.csv")
df_single_with_grps = df_single_no_grps.copy()

# Bin the 'age' variable into 'age_grp'
bins = [-np.inf, 19, 25, 30, 35, 40, 45, 50, 55, np.inf]
labels = ["<19", "20 to 24", "25 to 29", "30 to 34", "35 to 39", "40 to 44", "45 to 49", "50 to 54", "55+"]
df_single_with_grps['age_grp'] = pd.cut(df_single_no_grps['age'], bins=bins, labels=labels, right=False, include_lowest=True)
print("age_grp column added to df_single_with_grps.")

age_grp column added to df_single_with_grps.

In [ ]:
# Check df_single_with_grps
df_single_with_grps

In [74]:
# 6b. Create column salary_broader for plotly splits

# Define broader salary bands using match-case
def categorize_salary(salary):
    match salary:
        case x if x in ['15k and below', '15k+ to 25k', '25k+ to 35k']:
            return "35k and less"
        case x if x in ['35k+ to 45k', '45k+ to 55k', '55k+ to 65k', '65k+ to 75k']:
            return "35k+ to 75k"
        case x if x in ['75k+ to 85k', '85k+ to 95k', '95k+ to 100k']:
            return "75k+ to 100k"
        case x if x in ['100k+ to 125k', '125k+ to 250k', '250k and above']:
            return "100k and above"   
        case x if x == 'Not Applicable':
            return "Not Applicable"
        case _:
            return "Unknown"
df_single_with_grps['salary_broader'] = df_single_with_grps['salary'].apply(categorize_salary)
df_single_with_grps.to_csv("final_outputs_dir/df_single_with_grps.csv", index = False )
# df_single_with_grps.to_csv("csv_outputs_dir/df_single_with_grps.csv", index = False)
print("salary_broader column added to df_single_with_grps. ")

salary_broader column added to df_single_with_grps.

In [ ]:
# Check df_single_with_grps
df_single_with_grps

In [ ]:
# Check if any salary_broader == 'Unknown'
unknown_salary_check = df_single_with_grps[df_single_with_grps['salary_broader'] == "Unknown"][['resp_id', 'salary', 'salary_broader']]
unknown_salary_check

Empty DataFrame
Columns: [resp_id, salary, salary_broader]
Index: []

"""
# Mapping alternative for salary_broader column
salary_broader_map = {
    "15k and below":      "35k and less",
    "15k+ to 25k":       "35k and less",
    "25k+ to 35k":       "35k and less",
    "35k+ to 45k":       "35k+ to 75k",
    "45k+ to 55k":       "35k+ to 75k",
    "55k+ to 65k":       "35k+ to 75k",
    "65k+ to 75k":       "35k+ to 75k",
    "75k+ to 85k":       "75k+ to 100k",
    "85k+ to 95k":       "75k+ to 100k",
    "95k+ to 100k":      "75k+ to 100k",
    "a. 100k+ to 125k":  "100k and above",
    "b. 125k+ to 250k":  "100k and above",
    "c. 250k and above":          "100k and above",
}

df_base["salary_broader"] = df_base["salary"].map(salary_broader_map)
# Respondents with Not Applicable salary will map to NaN — already excluded upstream
"""

In [76]:
# 6c. Export df_single_with_grps
# To csv
df_single_no_grps.to_csv( csv_outputs_dir/ "df_single_no_grps.csv", index = False)
df_single_with_grps.to_csv( csv_outputs_dir/ "df_single_with_grps.csv", index = False)
df_single_with_grps.to_csv( final_outputs_dir/ "df_single_with_grps.csv", index = False)
# To parquet
df_single_with_grps.to_parquet(parquet_outputs_dir/"df_single_with_grps.parquet", index = False)

# 7. Handle multi-response columns
- Define multi_response_cols list
- Create explode_and_lookup function

In [6]:
# 0. Imports & Config
# ~~~~~~~~~~~~~~~~~~~~~~~~~
import pandas as pd
import unicodedata
from pathlib import Path
import numpy as np
import csv # so comma delimited values are not split
import datetime

In [2]:
# 0. Create Directories
# Store all lookup files for single-response columns and exploded multi-response csv files
lookup_dir = Path("lookup_dir")
lookup_dir.mkdir(exist_ok=True)

# Store all parquet files
parquet_outputs_dir = Path("parquet_outputs_dir")
parquet_outputs_dir.mkdir(exist_ok=True)

# Store all the outputs as csv so cleaning can be split into modules
csv_outputs_dir = Path("csv_outputs_dir")
csv_outputs_dir.mkdir(exist_ok=True)

# Copy of all the final outputs for data model
final_outputs_dir = Path("final_outputs_dir")
final_outputs_dir.mkdir(exist_ok=True)

# Store preliminary unique values
unique_dir = Path("unique_dir")
unique_dir.mkdir(exist_ok=True)

# Store all csv and map files using country and city columns
location_dir = Path("location_dir")
location_dir.mkdir(exist_ok = True)

In [4]:
# 7. Define and filter multi-response columns

# Import df_raw if starting this section again
df_raw = pd.read_parquet(parquet_outputs_dir/"df_raw.parquet")
df_raw

# Define multi-response columns
multi_response_cols = ["digitools", "successmethod", "restofrole", "ingestion", "transform", "storage", "warehs", "orchest", "busint", "cloudplat", "generaltools", "whatused", "ai_tools", "hardware", "dep_init", "volunteer", "spneeds", "otherfb", "attended_inperson", "attended_online"]

# filter using multi-response columns
df_raw_multi = df_raw[['resp_id'] + multi_response_cols].copy()
df_raw_multi.columns

Index(['resp_id', 'digitools', 'successmethod', 'restofrole', 'ingestion',
       'transform', 'storage', 'warehs', 'orchest', 'busint', 'cloudplat',
       'generaltools', 'whatused', 'ai_tools', 'hardware', 'dep_init',
       'volunteer', 'spneeds', 'otherfb', 'attended_inperson',
       'attended_online'],
      dtype='object')

In [ ]:
df_raw

# Special cleaning for MS Fabric response items with commas to avoid parsing at the commas

In [7]:
# 7a1. Remove comma in MS Fabric under ingestion
# print (df_raw_multi['ingestion'].unique())

# Replace the MS Fabric item
df_raw_multi['ingestion'] = df_raw_multi['ingestion'].str.replace("MS Fabric (Eventstreams, Dataflow, COPY, etc.)", "MS Fabric (Evenstreams Dataflow COPY)")

# Inspect again
# Filter the column first, then get unique values
ms_fabric_ingestion = df_raw_multi[df_raw_multi['ingestion'].str.contains("MS Fabric")]['ingestion']
print(ms_fabric_ingestion.unique())
print("Date and Time: ", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

['MS Excel, MS Fabric (Evenstreams Dataflow COPY), MS Power Platform, Power BI'
 'Azure Data Factory, MS Fabric (Evenstreams Dataflow COPY), MSSQL replication, Power BI, SSIS'
 'Alteryx, Amazon Kinesis, Apache Kafka, AWS Glue, AWS Lambda, Azure Data Factory, Azure Databricks, Azure Synapse Analytics, Databricks, Dataverse, Fivetran, Google Sheets, Google Cloud Composer, Google Cloud Dataflow, Hadoop, Knime, MS Excel, MS Fabric (Evenstreams Dataflow COPY), MS Forms, MS Power Platform, MSSQL replication, Oracle, Power BI, Python scripts, Salesforce, Snowflake, Spark, SQL, SSIS, Tableau Prep, Talend'
 'Azure Data Factory, Azure Databricks, Azure Synapse Analytics, Databricks, MS Fabric (Evenstreams Dataflow COPY), Power BI, Python scripts, Snowflake, Spark, SQL'
 'AWS Glue, Azure Databricks, MS Fabric (Evenstreams Dataflow COPY), MS Power Platform, Power BI, SQL, Tableau Prep'
 'Google Sheets, MS Excel, MS Fabric (Evenstreams Dataflow COPY), MS Forms, MS Power Platform, Tableau Prep'
 'AWS Glue, Azure Databricks, Databricks, Google Sheets, MS Excel, MS Fabric (Evenstreams Dataflow COPY), Power BI, Python scripts, Spark, SQL'
 'MS Excel, MS Fabric (Evenstreams Dataflow COPY), MS Power Platform, Power BI, SQL'
 'Alteryx, Azure Databricks, Databricks, MS Fabric (Evenstreams Dataflow COPY), Power BI, Python scripts, Spark, SQL, Tableau Prep'
 'Azure Data Factory, Custom tools, Dataverse, MS Fabric (Evenstreams Dataflow COPY), MS Power Platform, SQL'
 'Dataverse, MS Excel, MS Fabric (Evenstreams Dataflow COPY), MS Forms, MS Power Platform, Power BI'
 'Custom tools, MS Excel, MS Fabric (Evenstreams Dataflow COPY), Power BI'
 'Azure Data Factory, MS Fabric (Evenstreams Dataflow COPY)'
 'MS Excel, MS Fabric (Evenstreams Dataflow COPY), Power BI, Python scripts, SQL'
 'MS Excel, MS Fabric (Evenstreams Dataflow COPY), Power BI'
 'Apache Kafka, AWS Glue, AWS Lambda, Databricks, Hadoop, MS Fabric (Evenstreams Dataflow COPY), MS Power Platform, Power BI'
 'Amazon Kinesis, AWS Glue, AWS Lambda, Custom Python, MS Fabric (Evenstreams Dataflow COPY), Python scripts, SQL'
 'MS Excel, MS Fabric (Evenstreams Dataflow COPY), Power BI, None of the above'
 'MS Excel, MS Fabric (Evenstreams Dataflow COPY), MS Forms, MS Power Platform'
 'MS Excel, MS Fabric (Evenstreams Dataflow COPY), MS Forms, MS Power Platform, MSSQL replication, Power BI, SQL, SSIS'
 'MS Excel, MS Fabric (Evenstreams Dataflow COPY), Power BI, Salesforce, Tableau Prep'
 'MS Fabric (Evenstreams Dataflow COPY), Power BI, SQL'
 'MS Excel, MS Fabric (Evenstreams Dataflow COPY), Oracle, Python scripts, SSIS'
 'Alteryx, Custom Python, MS Excel, MS Fabric (Evenstreams Dataflow COPY), Oracle, Python scripts, Salesforce, SQL'
 'AWS Glue, AWS Lambda, Custom Python, Fivetran, MS Fabric (Evenstreams Dataflow COPY), Python scripts, SQL'
 'Custom tools, MS Excel, MS Fabric (Evenstreams Dataflow COPY), MS Forms, Power BI, SQL'
 'MS Excel, MS Fabric (Evenstreams Dataflow COPY), MS Power Platform, Python scripts'
 'Azure Data Factory, Azure Databricks, Custom Python, Databricks, MS Excel, MS Fabric (Evenstreams Dataflow COPY), Power BI, Python scripts, Snowflake, SQL, Talend'
 'Apache NiFi, MS Excel, MS Fabric (Evenstreams Dataflow COPY), MS Power Platform, MSSQL replication, Oracle, Power BI, SQL, SSIS, Tableau Prep'
 'Apache Kafka, AWS Glue, AWS Lambda, Azure Data Factory, Azure Databricks, Databricks, Hadoop, MS Fabric (Evenstreams Dataflow COPY), Power BI, Python scripts, Snowflake, Spark, SQL'
 'MS Excel, MS Fabric (Evenstreams Dataflow COPY), MS Power Platform, Power BI, Python scripts']
Date and Time:  2026-03-10 09:16:46

In [8]:
# 7a2. Remove comma in MS Fabric under orchestration
# print (df_raw_multi['orchest'].unique())

# Replace the MS Fabric item under orchestration
df_raw_multi['orchest'] = df_raw_multi['orchest'].str.replace("MS Fabric (Pipelines, etc.)", "MS Fabric (Pipelines)")

# Inspect again
ms_fabric_orchestration = df_raw_multi[df_raw_multi['orchest'].str.contains("MS Fabric")]['orchest']
print(ms_fabric_orchestration.unique())
print("Date and Time: ", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

['MS Fabric (Pipelines), SQL Server Agent'
 'Airflow, Astronomer, AWS Step Functions, Azure Data Factory, Cron, Databricks Workflows, GCP Cloud Workflows, Kubeflow, MS Fabric (Pipelines), MS Power Automate, SQL Server Agent, Windows Task Scheduler'
 'Airflow, MS Fabric (Pipelines), MS Power Automate'
 'AWS Step Functions, MS Fabric (Pipelines)' 'MS Fabric (Pipelines)'
 'Azure Data Factory, Databricks Workflows, MS Fabric (Pipelines)'
 'Databricks Workflows, MS Fabric (Pipelines), MS Power Automate'
 'MS Fabric (Pipelines), MS Power Automate'
 'Databricks Workflows, Kubeflow, MS Fabric (Pipelines)'
 'Azure Data Factory, MS Fabric (Pipelines), Orkes'
 'Azure Data Factory, MS Fabric (Pipelines)'
 'MS Fabric (Pipelines), MS Power Automate, SQL Server Agent'
 'Azure Data Factory, MS Fabric (Pipelines), MS Power Automate'
 'MS Fabric (Pipelines), MS Power Automate, Windows Task Scheduler, None of the above'
 'Azure Data Factory, MS Fabric (Pipelines), MS Power Automate, Sematic, SQL Server Agent, Windows Task Scheduler'
 'Azure Data Factory, Databricks Workflows, MS Fabric (Pipelines), MS Power Automate'
 'Airflow, MS Fabric (Pipelines), MS Power Automate, SQL Server Agent'
 'Airflow, Azure Data Factory, MS Fabric (Pipelines)'
 'Airflow, Kubeflow, MS Fabric (Pipelines)']
Date and Time:  2026-03-10 09:17:10

In [9]:
# 7a3. Remove comma in MS Fabric under transformation
# print (df_raw_multi['transform'].unique())

# Replace the MS Fabric item under transformation
df_raw_multi['transform'] = df_raw_multi['transform'].str.replace("MS Fabric (dbt-fabric, Dataflow, etc.)", "MS Fabric (dbt-fabric Dataflow)")

# Inspect again
ms_fabric_transformation = df_raw_multi[df_raw_multi['transform'].str.contains("MS Fabric")]['transform']
print(ms_fabric_transformation.unique())
print("Date and Time: ", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

['MS Fabric (dbt-fabric Dataflow), MS Power BI Dataflows, SQL-Based Platforms'
 'Alteryx, AWS Athena, AWS Glue, Azure Data Factory, Dataverse, Google BigQuery, Google Sheets, Informatica, Knime, MS Excel, MS Fabric (dbt-fabric Dataflow), MS Power Apps, Pandas, Polars, Postgresql, MS Power Automate, MS Power Query, MS Power BI Dataflows, Pyspark, Python, R, Spark, SQL-Based Platforms, SQL/Full SQL(BigQuery), SQL/PL/SQL(Oracle), SQL/Postgresql, SQL/Snowflake, SQL/SparkSQL(Databricks), SQL/T-SQL, SSIS, Tableau Prep, XSLT'
 'MS Excel, MS Fabric (dbt-fabric Dataflow), MS Power Apps, MS Power Automate, MS Power Query, MS Power BI Dataflows'
 'Azure Data Factory, MS Fabric (dbt-fabric Dataflow), Pyspark, Spark, SQL/Snowflake, SQL/SparkSQL(Databricks)'
 'Azure Data Factory, MS Fabric (dbt-fabric Dataflow), Python, SQL-Based Platforms'
 'Google Sheets, Informatica, MS Excel, MS Fabric (dbt-fabric Dataflow), MS Power Apps, R'
 'Azure Data Factory, MS Excel, MS Fabric (dbt-fabric Dataflow), SQL/Postgresql, SQL/T-SQL'
 'Azure Data Factory, Dataverse, MS Excel, MS Fabric (dbt-fabric Dataflow), MS Power Apps, SQL/T-SQL'
 'Dataverse, MS Excel, MS Fabric (dbt-fabric Dataflow), MS Power Apps, Mulesoft, MS Power Automate, MS Power Query, MS Power BI Dataflows'
 'Azure Data Factory, MS Fabric (dbt-fabric Dataflow), Pyspark, Python, Spark, SQL/SparkSQL(Databricks)'
 'MS Excel, MS Fabric (dbt-fabric Dataflow)'
 'MS Fabric (dbt-fabric Dataflow), MS Power Query, MS Power BI Dataflows'
 'MS Excel, MS Fabric (dbt-fabric Dataflow), MS Power Apps, Postgresql, SQL-Based Platforms, SQL/SparkSQL(Databricks)'
 'Azure Data Factory, MS Fabric (dbt-fabric Dataflow), MS Power BI Dataflows, SQL/T-SQL'
 'MS Excel, MS Fabric (dbt-fabric Dataflow), Python, SQL/Full SQL(BigQuery)'
 'MS Excel, MS Fabric (dbt-fabric Dataflow), MS Power Query, MS Power BI Dataflows'
 'MS Fabric (dbt-fabric Dataflow), MS Power Automate, MS Power Query, MS Power BI Dataflows'
 'MS Excel, MS Fabric (dbt-fabric Dataflow), MS Power Apps, MS Power Automate, MS Power Query, MS Power BI Dataflows, SQL/T-SQL, SSIS'
 'MS Excel, MS Fabric (dbt-fabric Dataflow), MS Power Automate, MS Power Query, MS Power BI Dataflows'
 'AWS Athena, MS Excel, MS Fabric (dbt-fabric Dataflow), Pandas, Python, SQL/Postgresql'
 'Google Sheets, MS Fabric (dbt-fabric Dataflow), Tableau Prep'
 'MS Excel, MS Fabric (dbt-fabric Dataflow), MS Power Automate, MS Power Query, MS Power BI Dataflows, Python, SQL/Postgresql'
 'Google BigQuery, MS Excel, MS Fabric (dbt-fabric Dataflow), Pyspark, Python, R, SQL/Full SQL(BigQuery)'
 'MS Excel, MS Fabric (dbt-fabric Dataflow), MS Power Apps, MS Power Automate, MS Power BI Dataflows'
 'Dataverse, MS Excel, MS Fabric (dbt-fabric Dataflow), MS Power Apps, MS Power Automate, MS Power Query, MS Power BI Dataflows, SQL-Based Platforms, SQL/T-SQL, SSIS'
 'Dataverse, MS Fabric (dbt-fabric Dataflow), MS Power Apps, Pandas, MS Power Automate, MS Power Query, MS Power BI Dataflows, Pyspark, Python'
 'Google BigQuery, MS Excel, MS Fabric (dbt-fabric Dataflow), Pandas, Postgresql, MS Power Automate'
 'Alteryx, MS Fabric (dbt-fabric Dataflow), Pandas, Postgresql, MS Power Automate, MS Power Query, Python, SQL-Based Platforms, SQL/PL/SQL(Oracle)'
 'MS Excel, MS Fabric (dbt-fabric Dataflow), MS Power Automate, MS Power Query, MS Power BI Dataflows, SQL-Based Platforms, SQL/Postgresql'
 'Azure Data Factory, dbt, MS Excel, MS Fabric (dbt-fabric Dataflow), Pandas, Pyspark, Python, Spark, SQL-Based Platforms, SQL/T-SQL'
 'AWS Athena, AWS Glue, Azure Data Factory, dbt, MS Fabric (dbt-fabric Dataflow), Postgresql, Pyspark, Python, SQL/Snowflake, SQL/SparkSQL(Databricks)'
 'MS Excel, MS Fabric (dbt-fabric Dataflow), MS Power Apps, Pandas, MS Power Query, MS Power BI Dataflows, Python']
Date and Time:  2026-03-10 09:17:20

In [58]:
# 7b. Special cleaning for attended inperson and online - clean and standardize None responses
# Using fuzzy match
cols_attended = ['attended_inperson', 'attended_online']

for col in cols_attended:

    # Fuzzy match patterns
    mask_fuzzy = df_raw_multi[col].str.lower().str.contains(
        r'non|none|nope|n/a',
        na=False
    )

    # Exact none-like values
    mask_exact = df_raw_multi[col].str.strip().str.lower().isin([
        'nan',
        '/a',
        'n/a',
        'nope',
        'no e',
        'npne',
        'nine',
        'nin',
        'n n'
    ])

    # True NaN values
    mask_nan = df_raw_multi[col].isna()

    # Combine all masks
    mask_combined = mask_fuzzy | mask_exact | mask_nan

    # Replace with standard value
    df_raw_multi.loc[mask_combined, col] = 'None'

    # Final normalization
    df_raw_multi[col] = df_raw_multi[col].str.strip().str.upper()

    # Print unique values
    unique_list_attended= sorted(set(df_raw_multi[col].to_list()))
    print(f"Unique values in {col}")
    print("~"*40)
    print(unique_list_attended)
    print("~"*40, "\n\n")

# Export df_raw_multi to csv
df_raw_multi.to_csv(csv_outputs_dir/"df_raw_multi.csv", index = False)  
df_raw_multi.to_parquet(parquet_outputs_dir/"df_raw_multi.parquet", index = False)
print("Date and Time: ", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

Unique values in attended_inperson
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
['"NEXT-GEN JAVA: AI, CLOUD, & PERFORMANCE" SEMINAR', '2025 PHILIPPINE JUNIOR DATA SCIENCE CHALLENGE', '2ND MEET UP IN CBTL', 'AIBP CONVENTION, DATA STREAMS WORKSHOPS', 'ATTENDED A SEMINAR ORGANIZED BY AI PILIPINAS', 'AWS CLOUD DAY', 'AWS COMMUNITY DAY', 'AWS INNOVATION CUP', 'AWS STUDENT COMMUNITY NIGHT', 'BIBE', 'BIG DATA EUROPE', 'BPI DATA WAVE, DICT PSC', 'BPI WAVE HACKATHON', 'CTRL ALT RUN', 'DATA ENGINEERING BULACAN MEETUP', 'DATA FUTURE PHILIPPINES 2025', 'DAXDAKAN', 'DAXDAKAN LIVE', 'DEEPLEARNING.AI HACKATHON', 'DEP DECEMBER CONFERENCE', 'DEP SOUTH MEETUP', 'DEVCON', 'DEVCON MORE ABOUT ON AI', 'DICT STARTUP CONTEST', 'DSA ONLINE TRAINING', 'EHEADS', 'EHEADS, PYCON APAC 2025, AI PIE MANILA', 'EHEADS20', 'FEU TECH CS EXPO', 'FREE WEBINARS, SHORT COURSES ONLINE', 'FTW FOUNDATION DATA ANALYTICS PROGRAM', 'GDG GOOGLE DEV SEMINARS AND WORKSHOPS', 'GOOGLE DEV FEST', 'GOOGLE DEVFEST 2025', 'GOOGLE DEVFEST DAVAO 2025', 'GOOGLE IO EXTENDED MANILA', 'HACKATHON HOSTED IN HOLY ANGEL UNIVERSITY, HAU-GDG', 'HEXCORE LABS AI HACKATHON', 'HYBRID SCHOLARSHIP.', 'I FORGOT THE TITLE', 'I JOINED, ASEAN DATA SCIENCE EXPLORERS ENABLEMENT', 'ICT CONGRESS', 'IMPORTANCE OF DATA VISUALIZATION ON MEETUP GROUP', 'INTERNSHIP', 'IOT CONFERENCE PHILIPPINES', 'IVE GAINED CERTIFICATES ON SQL', 'JAVASCRIPT & HACKATHON SEMINAR', 'JUST STUDYING IN DATACAMP', 'KOBOTOOLBOX WORKSHOP', 'LIMITLESS: NATIONAL YOUTH SUMMIT ON STATISTICS', 'MEETUP', "MODERATORS' MEETUP", 'NATIONAL PLANNING INSTITUTE OF EGYPT', 'NOJE', 'NONE', 'NOT APPLICABLE', 'ONLINE DATA SENSE ANALYTICS EVENT', 'ONLINE FOR ZOOMCAMP', 'ORGANIZE HACKATON EVENT, RAG WORKSHOP MENTOR', 'PHILIPPINE BLOCKCHAIN EVENT', 'PHILIPPINE JUNIOR DATA SCIENCE CHALLENGE', 'PJDSC DATA SCIENCE CHALLENGE', 'POWER BI PILINAS EVENTS', 'POWER BI WITH QAFZA', 'POWERBI PILIPINAS MEETUP', 'PYCON DAVAO', 'PYCON DAVAO 2025', 'PYLADIES EVENT, IDOL MERALCO HACKATHON', 'R USER GROUP - PHILIPPINES', 'RAITE 2025', 'RESEARCH CONVENTION ON WEB AND DATA SCIENCE', 'SAME AS ABOVE.', 'SOSCON', 'SOSCON 2025', 'SOSCON PH 2025', 'STARTUP AWARENESS ACTIVITIES', 'TECHBAYANIHAN', 'TECHBAYANIHAN 2025', 'TECHBAYANIHAN 2026', 'TRACKTECH HACKATHON 2026', 'UP COMMUNITY OF DATA EXPERTS: DATA TALKS', 'UP NEC', 'UPMIN AWS CLUD CLUB AWS RE:INVENT RE:CAP', 'VOLUNTEER IN EHEADS 20, ATTENDED EHEADS21,VIBEHIVE', 'VOLUNTEER ON EHEADS', 'WESTERN VISAYAS AI HACKATHON', 'WITNESSED THE CAPSTONE PRESENTATION OF FTW B11', 'WPH HACKATHON 2025']
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Unique values in attended_online
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
['A BOOTCAMP ON GOHIGHLEVEL', 'A NVIDIA WEBINAR ON DEEP LEARNING', 'AI ENGINEER AND SOME COURSE.', 'AKUNI WEBINAR "UNLOCKING THE POWER OF DATA"', 'ALEX THE ANALYST FREE BOOTCAMP IN YOUTUBE', 'ALL FREE WEBINARS AND WORKSHOP IN DSA ORG', 'ATTENDED THE GRADUATION OF FTW (CAPSTONE) BATCH 11', 'AWS CLOUD TECHNOLOGY AND SERVICES CONCEPTS', 'AZ-900 CERTIFICATION', 'BREAKING INTO TECH', 'CAREER BOOST WITH POWER BI AND AI (FREE WEBINAR)', 'CAREER SHIFTING AND DATA ANALYSIS DISCORD MEETING', 'CISCO FREE COURSES', 'CISCO NETACAD\'S COURSE "INTRODUCTION TO MODERN AI"', 'CISCO NETWORK ACADEMY COURSES, DICT COURSES', 'COURSERA', 'COURSERA FREE TRIAL', 'CRASH COURSE POWER BI', 'DAPH: DATA FUTURE PH 2025', 'DATA ANALYTICS PHILIPPINES - INTRO TO POWER BI', 'DATA ANALYTICS PHILIPPINES INTRODUCTION POWER BI', 'DATA ANALYTICS PHILIPPINES POWER BI', 'DATA ASTERS', 'DATA CAMP COURSES', 'DATA CERTIFICATION GOOGLE IN COURSERA', 'DATA ENGINEERING ZOOMCAMP ORIENTATION', 'DATA FUTURE PH 2025', 'DATA MASTERS', 'DATA MASTERS - RESUME REVIEW & INTERVIEW PRACTICE', 'DATA MASTERS: RESUME REVIEW', 'DATA SCIENCE CISCO COURSE OFFERED BY DICT', 'DATA SCIENCE ONLINE BOOTCAMP (DIRECHO TRABAHO)', 'DATA SCIENCE PREPARATORY COURSE FROM MY WORK', 'DATA SENSE ANALYTICS- INTRO TO POWERBICRASH COURSE', 'DATA SENSE FREE WEBINAR, XCEL HUB FREE WEBINAR', 'DATABRICKS WEBINAR', 'DATACAMP', 'DATACAMP ASSIGNMENTS, TECH RADAR AT DATA CAMP', 'DATACAMP COURSE', 'DATACAMP DATA ENGINEERING COURSE', 'DATACAMP SCHOLARSHIP', 'DATACAMP WEBSITE ONLY I SELF STUDY', 'DATACAMP, DATABRICKS LIVE COURSE', 'DATACAMP. COURSERA. YOUTUBE. FREE WEBINARS', 'DATACAMPS DCHOLARSHIP', 'DATAFUTUREPH2025', 'DATAMASTERS', 'DATAMASTERS AND AI STUDY GROUP', 'DATAMASTERS _ RESUME REVIEW AND INTERVIEW PRACTICE', 'DATASENCW', 'DATASENSE POWER BI WEBINAR', 'DAXDAKAN', 'DEC', 'DEP ASSIGNMENT IN DATACAMP', 'DEP DATA MASTERS: RESUME REVIEW', 'DEP DECEMBER CONFERENCE', 'DEP FREE WEBINAR', 'DEP LEADERSHIP MEETING', 'DEP MEETUP -> RESUME ROASTING', 'DEP PODCAST', 'DEP PODCAST VIA DISCORD', 'DEP SCHOLAR', 'DEP SPONSORED CLASS AT DATACAMP', 'DEP STUDY GROUP, DATAMASTERS', 'DEP TAMBAYAN/PODCAST', 'DEP VOLUNTEER PROGRAM', 'DEP X DATA CAMP', 'DEP X DATACAMP 2025', 'DICORD', 'DICT', 'DISCORD', 'DISCORD - A TALK BY SIMONEE MARIQUIT', 'DISCORD EPISODE 2 TAMBAYAN NG DEP SEPT 27', 'DISCORD EVENT', 'DISCORD EVENT - DATAMASTERS', 'DISCORD EVENT ABOUT THEIR PROJECTS', 'DISCORD EVENT AND FREE WEBINAR', 'DISCORD EVENT!', 'DISCORD EVENT, AND SOME WEBINAR', 'DISCORD EVENT, DEP SOUTH MEETUP, DE YEAR 2 MEETUP', 'DISCORD EVENT, FREE WEBINAR', 'DISCORD EVENT, IMPORTANCE OF DATA VISUALIZATION', 'DISCORD EVENT, PRESENTATION', 'DISCORD EVENT: PODCAST, MEETUPS, ETC', 'DISCORD EVENTS', 'DISCORD EVENTS PARTICULARLY THE DATA MASTERS', 'DISCORD FREE WEBINAR', 'DISCORD MEEETUPS', 'DISCORD PRESENTATIONS', 'DISCORD WEBINAR', 'DOMO IN THE KNOW. DOMO POWER USERS.', 'DOST WEBINAR', 'DSA ONLINE TRAINING', 'EDA PRESENTATION', 'ESKWELABS BOOTCAMP AND DATAMASTERS', 'ESKWELABS WEBINAR', 'EVENT FROM DATA SENSE', 'EVENTS AT MY COMPANY, PROMPT ENGINEERING', 'EXODUS EXPERTS - CAREER BOOST WITH POWER BI', 'EXPLORATORY DATA ANALYSIS OF A POKEMON DATASET', 'FB PAGE', 'FREE COURSE IN DA', 'FREE COURSES IN UDEMY', 'FREE POWER BI WEBINAR FOR BEGINNERS', 'FREE TRAINING', 'FREE WEBINAR', 'FREE WEBINAR ABOUT DATA ANALYTICS', 'FREE WEBINAR ABOUT DATA ENGINEERING.', 'FREE WEBINAR ABOUT POWER BI', 'FREE WEBINAR AND DISCORD EVENT', 'FREE WEBINAR AND ZOOM MEETING', 'FREE WEBINAR FOR THE SCHOLARSHIP FOR DP900', 'FREE WEBINAR FROM DEP', 'FREE WEBINAR IN OUR SCHOOL', 'FREE WEBINAR IN OUR UNIVERSITY', 'FREE WEBINAR OF DATASENSE ANALYTICS', 'FREE WEBINAR ON DATA ANALYTICS', 'FREE WEBINAR ON DATACAMP', 'FREE WEBINAR ON POWERBI', 'FREE WEBINAR, YOUTUBE', 'FREE WEBINAR/COURSE', 'FREE WEBINARS', 'FREE WEBINARS, DATA PRIVACY AND DATA SECURITY', 'FREE WEBINARS, FREE LIVE YOUTUBE COURSE', 'FREE WEBINARSNO', 'FREE WEBMINAR', 'FREE WEBNAR', 'FTW FOUNDATION DATA ANALYTICS PROGRAM', 'GDG GOOGLE DEV SEMINARS AND WORKSHOPS', 'GEN AI ACADEMY 2.0', 'GOOGLE DATA ANALYTICS PROFESSIONAL CERTIFICATE', 'I AM JUST FOCUSING ON USING DATACAMP TO STUDY.', 'I AM ONE WHO GOT DATA CAMP SCHOLARSHIP', 'I ATTENDED A WEBINAR ABOUT WEB 3.0', 'I ATTENDED A WEBINAR HOSTED BY MY SCHOOL.', 'I ATTENDED TO AWS SEMINARS AND GDGOC SEMINARS', 'I FORGOT', 'I HAVE ATTENDED A LOT OF EVENTS ON DISCORD', 'I HAVE ATTENDED A WEBINAR ON DISCORD.', 'I HAVE ATTENDED WEBINARS AND WATCHING YOUTUBE.', 'I JOIN GROUP STUDY IN DISCORD.', 'I WATCHED DATASENSE VIDEOS AND JOINED FB GROUPS', 'ICPEP GENERAL ASSEMBLY', 'IEMBE ATTENDED SEMINARS ABOUT AI', 'IM NOT SURE IF WATCHING AN ONLINE COURSE COUNTS.', 'IMB COURSE', 'IN MY WORK, I WAS TASKED TO TAKE DA COURSE', 'INTRO TO DATA ANALYTICS - WITH ABRAHAM AVILA JR.', 'INTRO TO DATA SCIENCE COURSE', 'INTRODUCTION TO DATA ANALYTICS', 'INTRODUCTION TO MINITAB- INNOVPH', 'INTRODUCTION TO PYTHON BY DSA', 'IT IS A MEETING IN DISCORD MORE ON KAMUSTAHAN', 'IT PHILIPPINES', 'IT WAS A WEBINAR POSTED FROM THE DISCORD SERVER', 'JOINED IN SOME CHALLENGES PREVIOUSLYTH', 'JUST STUDYING IN DATACAMP', 'LEAN SIX SIGMA TRAINING, DATA ANALYST SERIES, ETC.', 'LEARN USING DATACAMP. JOINED ONLINE CONTESTS', 'LEARNING THROUGH DATACAMP SCHOLARSHIP', 'LECTURE SERIES - QUANTUM COMPUTING CYBERSECURITY.', 'MEETUP', 'MEETUP EVENTS BY DEP', 'MENTORSHIP. I HAVE 2 MENTEES I MEET UP REGULARLY', 'MICROSOFT FABRIC FUNDAMENTALS (APAC)', 'MICROSOFT PUP ORIENTATION', 'MICROSOFT REACTOR EVENT', 'MLH BEGINNERS WEEK', 'MOCK INTERVIEW', 'MY DATA SCIENCE COURCE WHICH I ENNROLLED LAST SEM', 'NATIONAL ICT MONTH', 'NKNE', 'NOME', 'NONE', 'NOT APPLICABLE', 'NOT UNDER DEP BUT DATABRICKS WEBINAR', 'ONLINE', 'ONLINE COURSE', 'ONLINE COURSE WORK', 'ONLINE COURSES', 'ONLINE DATACAMP COURSE, WEBINAR', 'ONLINE SQL TRAINING SESSION', 'ONLINE TRAINING ON AI WORKFLOW AUTOMATION', 'P&G IT CASE STUDY', 'PBI & EXCEL BOOTCAMP, PL300/AI102/DP600 TRAINING', 'PODCAST, DATAMASTERS, AI STUDY GROUP', 'POWER BI 2025 COMPETITITION ANNOUNCMENT OF RESULTS', 'POWER BI CRASH COURSE', 'POWER BI INTRODUCTION', 'POWER BI OVERVIEW', 'POWER BI PILINAS EVENTS', 'POWER BI WITH QAFZA', 'PREVIOUS DATACAMP SCHOLARSHIP', 'PREVIOUS WORK', 'PYTHON LEVEL 3 COURSE BY EXCELHELPLINE', 'REGARDING SQL', 'RESUME REVIEW & INTERVIEW PRACTICE', 'RESUME ROASTING', 'SCHOLARSHIP', 'SCHOOL SEMINARS ABOUT GENERATIVE AI AND ROBOTICS', 'SCHOOL TECH-RELATED SEMINAR FROM SPEAKERS OF AWS', 'SELF-HOSTED WEBINAR FOR DATA ENGINEERING', 'SELF-PACED LEARNING OF N8N IN YOUTUBE', 'SEMINARS FROM UPLB', 'SHOWCASE OF DASHBOARDS BY THE COMMUNITY', 'SOMETHING ON CAREER TALKS', 'SQL SEMINAR IN DATACAMP', 'STUDIED DATA ANALYTICS THRU DATA CAMP', 'STUDY GROUP IN DISCORD', 'TAMBAYAN NG DEP EPISODE 2 (VIA DISCORD)', 'TEAMS CHAT COPILOT LOG IN ASSISTANCE', 'TECHBAYANIHAN', 'TECHBAYANIHAN 2025', 'TECHBAYANIHAN 2026', "THE TALK ABOUT SURVEY RESULTS, AND MYK'S JOURNEY", 'THIS DATAMASTERS THAT WAS A DISCORD EVENT.', 'THRU DATE CAMP', 'TUTORIAL ON SETTING UP CHAINLIT AND LANGCHAIN', 'UP DATA SCIENCE SOCIETY WORKSHOP', 'UP INTELLIGENT SYSTEMS CENTER WEBINAR SERIES', 'UPDSSOC FREE WEBINAR', 'VECTOR DATABASES 101', 'WATCHED RECORDED FACEBOOK LIVE FROM DEP', 'WATCHED VIDEOS REGARDING BEGINNER SQL', 'WEBINAR', 'WEBINAR (DATA ANALYTIC PHILIPPINES', 'WEBINAR (NOT DEP)', 'WEBINAR ABOUT DATA SCIENCE (FROM UPD)', 'WEBINAR AI UPSKILLING , GENERATIVE AI', 'WEBINAR FROM DATA SCIENCE UP SOCIETY VIA FACEBOOK', 'WEBINARS, TRAINING, SQL TRAINING,', 'YOUTUBE DATA VIDEOES, AND CISCO COURSEE', 'YOUTUBE FREE DATA ANALYSIS TUTORIALS', 'ZACH WILSON FREE DATA ENGINEERING ZOOM CAMP']
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Date and Time:  2026-03-10 12:17:36

In [16]:
# 7c. Transform and normalize string values, explode and normalize functions for multi-response columns

# Transform string values (nested function inside explode and normalize)
def normalize_text(val):
    if pd.isna(val):
        return ""
    val = unicodedata.normalize("NFKC", str(val))
    val = val.strip()
    val = " ".join(val.split())
    return val


def explode_and_normalize(df, column):
    # Include resp_id and multi-response columns
    exploded = (
        df[["resp_id", column]]
        .assign(**{column: df[column].str.split(",")})
        .explode(column)
    )
    exploded[column] = exploded[column].apply(normalize_text)

    # Remove duplicates (resp_id, value) pairs
    exploded = exploded.drop_duplicates(subset=["resp_id", column], keep="first")

    exploded.to_parquet(parquet_outputs_dir / f"{column}_exploded.parquet", index = False)
    exploded.to_csv(csv_outputs_dir/f"{column}_exploded.csv", index = False)
    return exploded

print("Functions normalize_text and explode and normalize created")
print("Date and Time: ", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

Functions normalize_text and explode and normalize created
Date and Time:  2026-03-10 09:36:21

In [17]:
# 7d. Apply explode_and_normalize function → csv, parquet

# Now that the multi-response columns are cleaned, initialize df_multi dataframe from df_raw_multi

df_raw_multi=pd.read_csv(csv_outputs_dir/"df_raw_multi.csv")
df_multi = df_raw_multi[["resp_id"] + multi_response_cols].copy()

# Initialize the df_multi csv file
df_multi.to_csv(csv_outputs_dir / "df_multi.csv", index=False)

# Explode each multi-response column
for col in multi_response_cols:
    # Explode and lookup for this column
    df_exploded = explode_and_normalize(df_multi, col)

    # Export exploded dataframe as {col}_exploded.csv and parquet
    df_exploded.to_csv(csv_outputs_dir / f"{col}_exploded.csv", index=False)
    df_exploded.to_parquet(parquet_outputs_dir / f"{col}_exploded.parquet", index=False)

print("Multi-response columns exploded → csv, parquet.")
print("Date and Time: ", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

Multi-response columns exploded → csv, parquet.
Date and Time:  2026-03-10 09:36:34

In [18]:
# 7e. Special cleaning for datarole and restofrole 
# Check datarole duplicates by merging datarole and restofrole
# If datarole and restofrole are the same, then they are duplicates
# Create helper column
df_restofrole_exploded = pd.read_csv(csv_outputs_dir/"restofrole_exploded.csv")
df_single_with_grps = pd.read_csv(csv_outputs_dir/"df_single_with_grps.csv")
df_datarole = df_single_with_grps[['resp_id', 'datarole']]
df_role_merged = df_datarole.merge(df_restofrole_exploded, on = 'resp_id', how = 'inner')
df_role_merged['duplicated'] = (
    df_role_merged['datarole'].str.strip().str.lower()
    == df_role_merged['restofrole'].str.strip().str.lower()
)


# Drop duplicated rows in df_role_merged
df_role_merged = df_role_merged[df_role_merged['duplicated'] == False]

# Drop the helper column
df_role_merged = df_role_merged.drop(columns=['duplicated'])
df_role_merged.to_csv(csv_outputs_dir/"df_role_merged.csv", index = False)


# Create an updated restofrole exploded csv with a longer name and shorter name - for general cleaning later
df_restofrole_before_general_cleaning = df_role_merged[['resp_id', 'restofrole']].copy()
df_restofrole_before_general_cleaning.to_csv(csv_outputs_dir/"restofrole_exploded_before_general_cleaning.csv", index = False)
df_restofrole_before_general_cleaning.to_csv(csv_outputs_dir/"restofrole_exploded.csv", index = False)

print("Date and Time: ", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print("Special cleaning of restofrole done.")

Date and Time:  2026-03-10 09:36:56
Special cleaning of restofrole done.

In [59]:
# 7f. Second round of clean up multi-response columns after being exploded, especially the None variants

multi_response_cols = ["digitools", "successmethod", "restofrole", "ingestion", "transform", "storage", "warehs", "orchest", "busint", "cloudplat", "generaltools", "whatused", "ai_tools", "hardware", "dep_init", "volunteer", "spneeds", "otherfb", "attended_inperson", "attended_online"]

none_variants = [
    "None", "None ", "Non", "non", "non ", "npne", "n ne", "npn", "nine", "nin", "nond", "nonf"]

for col in multi_response_cols:
    path = csv_outputs_dir / f"{col}_exploded.csv"
    df_exp_cln = pd.read_csv(path)

    # Convert to string, strip spaces
    df_exp_cln[col] = df_exp_cln[col].astype("string").str.strip()

    # First, standardize blank-like values replace with pd.NA
    df_exp_cln[col] = df_exp_cln[col].replace(
        ["", "nan", "NaN"], pd.NA
    )

    # Then, normalize None-like strings to "None"
    df_exp_cln[col] = df_exp_cln[col].replace(none_variants, "None")

    # Drop rows where the exploded value is NA
    df_exp_cln = df_exp_cln.dropna(subset=[col])

    # Drop blanks
    df_exp_cln = df_exp_cln[df_exp_cln[col] != ''    ]

    # Save cleaned version
    df_exp_cln.to_csv(csv_outputs_dir / f"{col}_exploded_cleaned.csv", index=False)
    df_exp_cln.to_parquet(parquet_outputs_dir / f"{col}_exploded_cleaned.parquet", index=False)

print("Date and Time: ", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print("Second round of cleaning of multi-response columns done.")

Date and Time:  2026-03-10 12:18:21
Second round of cleaning of multi-response columns done.

In [60]:
# 7g. Summary of cleaned multi-response columns
# Recall the multi-response columns definition
multi_response_cols = [
    "digitools", "successmethod", "restofrole", "ingestion", "transform",
    "storage", "warehs", "orchest", "busint", "cloudplat", "generaltools",
    "whatused", "ai_tools", "hardware", "dep_init", "volunteer", "spneeds",
    "otherfb", "attended_inperson", "attended_online",
]

# Initialize the summary_frames list for pd.concat later
summary_frames = []

# Build summary of cleaned multi-response columns
def build_summary_multi(col):
    for col in multi_response_cols:
        # Build summary for this column
        path = csv_outputs_dir / f"{col}_exploded_cleaned.csv"
        df_exploded = pd.read_csv(path)

        # Remove duplicates on (resp_id, col) pair, retain first
        df_exploded = df_exploded.drop_duplicates(subset=["resp_id", col], keep="first")

        value_counts = df_exploded[col].value_counts(dropna=False).reset_index()
        value_counts.columns = ["value", "count"]
        value_counts.insert(0, "column", col)
        summary_frames.append(value_counts)

        # Divider row
        divider = pd.DataFrame([{"column": "~" * 50, "value": "", "count": ""}])
        summary_frames.append(divider)

# Call build summary        
build_summary_multi(multi_response_cols)

# Combine all summaries and export
summary_combined = pd.concat(summary_frames, ignore_index=True)
summary_combined.to_csv(csv_outputs_dir / "multi_response_summary.csv", index=False)

print("Summary of exploded cleaned tables created.")
print("Date and Time: ", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

Summary of exploded cleaned tables created.
Date and Time:  2026-03-10 12:18:26

In [61]:
#7i. Check similarity of df_possible_duplicates including multi-response columns
# Load dfs -> possible duplicates (single), merge with multi-response cols 
# -> split items list from string → "" blanks →  strip spaces  → sort → ", ".join to string
# Exploded files are unchanged.

df_possible_duplicates = pd.read_csv(csv_outputs_dir/"df_possible_duplicates.csv")
df_multi = pd.read_csv(csv_outputs_dir/"df_multi.csv")
df_likely_dups = pd.read_csv(csv_outputs_dir/"df_likely_dups.csv")

multi_response_cols = [
    "digitools", "successmethod", "restofrole", "ingestion", "transform",
    "storage", "warehs", "orchest", "busint", "cloudplat", "generaltools",
    "whatused", "ai_tools", "hardware", "dep_init", "volunteer", "spneeds",
    "otherfb", "attended_inperson", "attended_online"
]

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Merge df_possible_duplicates with df_multi FIRST (inner join)
# This keeps only respondents present in both tables
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

df_merged_dups = df_possible_duplicates.merge(
    df_multi[["resp_id"] + multi_response_cols],
    on="resp_id",
    how="inner"
)

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Standardization function for multi-response columns
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

def standardize_multi_response(s):
    if pd.isna(s) or s.strip() == "":
        return ""
    items = [x.strip() for x in s.split(",")]
    items = sorted([x for x in items if x != ""])
    return ", ".join(items)

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Apply standardization ONLY to the merged subset
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

for col in multi_response_cols:
    df_merged_dups[col] = df_merged_dups[col].apply(standardize_multi_response)

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Build explicit duplicate pairs from df_likely_dups
# Each row has resp_id and a list like [577]
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

resp_b = df_likely_dups["best_match_resp_ids"].str.strip("[] ").astype(int)

df_pairs = pd.DataFrame({
    "resp_id_1": df_likely_dups["resp_id"].combine(resp_b, min),
    "resp_id_2": df_likely_dups["resp_id"].combine(resp_b, max),
}).drop_duplicates()


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Compare multi-response columns for each pair
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

results = []

for _, row in df_pairs.iterrows():
    id1 = row["resp_id_1"]
    id2 = row["resp_id_2"]

    row_a = df_merged_dups[df_merged_dups["resp_id"] == id1].iloc[0]
    row_b = df_merged_dups[df_merged_dups["resp_id"] == id2].iloc[0]

    comparison = {
        "resp_id_1": id1,
        "resp_id_2": id2,
    }

    for col in multi_response_cols:
        comparison[col] = (row_a[col] == row_b[col])

    results.append(comparison)

# Convert results list to dataframe
df_multi_compare = pd.DataFrame(results)
df_multi_compare['count_true'] =df_multi_compare[multi_response_cols].sum(axis=1)
df_multi_compare['count_false'] = df_multi_compare.shape[1] - df_multi_compare['count_true']

df_multi_compare.to_csv(csv_outputs_dir/"df_multi_compare.csv", index = False)
print("Date and Time: ", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print("Duplicate check using multi-response columns done.")

Date and Time:  2026-03-10 12:18:58
Duplicate check using multi-response columns done.

In [64]:
# Full duplicate test
print(df_multi_compare[['resp_id_1', 'resp_id_2', 'count_true', 'count_false']])

print("~"*75)
print("If count_false > 0, then resp1 and resp2 are not duplicates.")
print("~"*75, "\n")

# Check for possible duplicates
if (df_multi_compare['count_false'] == 0).any():
    print("Possible duplicates found.")
else:
    print("No possible duplicates.")

print("Date and Time: ", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print("~"*75, "\n")


# Second run - multi-response columns are different. Nothing to delete.

    resp_id_1  resp_id_2  count_true  count_false
0        1727       1728          11           12
1         101        357          12           11
2         471        502          11           12
3        1099       1574          11           12
4        1123       1628          13           10
5         343       1382          10           13
6         337        577          11           12
7         592       1120          12           11
8         705       1081          11           12
9         306       1031          17            6
10        202        781          10           13
11        839       1285          10           13
12        845       1211          10           13
13        239       1418          11           12
14        961       1419          12           11
15        218       1315          12           11
16       1534       1624          13           10
17        195       1189          12           11
18        198       1337          13           10
19       1190       1338          10           13
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
If count_false > 0, then resp1 and resp2 are not duplicates.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

No possible duplicates.
Date and Time:  2026-03-10 12:22:29
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# 8.  Lineage - location dfs

- df_loc_new <- df_single_with_groups
- df_ph_grp, df_non_ph_grp <- df_loc_new 
- overseas <- df_ph_grp 
- df_ph_geo_clean <- df_ph_geo
- df_non_ph_geo_clean <- df_non_ph_geo
- df_all_geo_clean <- df_ph_geo_clean, df_non_ph_geo_clean

In [34]:
# 8. Load df_loc_new and save
# ~~~~~~~~~~~~~~~~~~~~~~~~~
df_single_with_grps = pd.read_csv(csv_outputs_dir/ "df_single_with_grps.csv")
df_loc_new = df_single_with_grps[["resp_id", "country", "city_ph", "city_non_ph"]].drop_duplicates()

location_dir = Path("location_dir")
location_dir.mkdir(exist_ok = True)
df_loc_new.to_csv(location_dir/ "df_loc_new.csv", index = False)

df_loc_new.info()
print("Date and Time: ", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1732 entries, 0 to 1731
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   resp_id      1732 non-null   int64
 1   country      1732 non-null   object
 2   city_ph      1732 non-null   object
 3   city_non_ph  1732 non-null   object
dtypes: int64(1), object(3)
memory usage: 54.2+ KB
Date and Time:  2026-03-10 10:35:30

In [40]:
# 8a. Check non-ph cities
# If Prefer Not To Say or Not Applicable change to capital city later using lookup
not_in_ph = df_loc_new[df_loc_new['country'] != "Philippines"]
print("Date and Time: ", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print("~"*50)
not_in_ph

Date and Time:  2026-03-10 10:44:18
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      resp_id               country         city_ph         city_non_ph
5           6        United Kingdom  Not Applicable           Newcastle
20         21        United Kingdom  Not Applicable              London
157       158                Norway  Not Applicable                Oslo
183       184              Cameroon  Not Applicable              Douala
232       233              Cambodia  Not Applicable          Phnom Penh
304       305              Thailand  Not Applicable             Bangkok
319       320              Pakistan           Diplo               Diplo
396       397  United Arab Emirates  Not Applicable                 UAE
543       544                Canada  Not Applicable   Prefer Not To Say
741       742                Canada        Caloocan      Not Applicable
762       763                 Nepal  Not Applicable      Not Applicable
782       783         United States  Not Applicable              Kansas
784       785                   Uae  Not Applicable               Dubai
825       826               Nigeria  Not Applicable               Lagos
831       832        United Kingdom  Not Applicable      Not Applicable
845       846                Jordan           Amman               Amman
847       848                Canada  Not Applicable              Regina
907       908  United Arab Emirates  Not Applicable               Dubai
911       912               Nigeria  Not Applicable      Not Applicable
1003     1004               Nigeria  Not Applicable          Benin City
1004     1005  United Arab Emirates         Aleosan           Abu Dhabi
1048     1049                 Egypt  Not Applicable      Not Applicable
1073     1074                 Egypt  Not Applicable               Cairo
1084     1085                 Egypt           Cairo               Cairo
1085     1086          Saudi Arabia         Bulacan                 KSA
1095     1096          South Africa       Cape Town           Cape Town
1099     1100                 Nepal  Not Applicable           Kathmandu
1125     1126                Uganda  Not Applicable  Soroti City Uganda
1185     1186                 Egypt      Alexandria          Alexandria
1206     1207         United States         Aleosan          Alexandria
1254     1255                 Egypt  Not Applicable               Cairo
1258     1259                 Congo        Kinshasa            Kinshasa
1279     1280                Uganda  Not Applicable      Not Applicable
1296     1297           South Korea     South Korea       Cheongju City
1311     1312              Malaysia  Not Applicable        Kuala Lumpur
1325     1326            Bangladesh  Not Applicable            Barishal
1389     1390                 Yemen  Not Applicable              Sana'A
1454     1455          Saudi Arabia  Not Applicable              Jeddah
1461     1462               Nigeria  Not Applicable             Ughelli
1473     1474                  Peru  Not Applicable               Pasco
1479     1480               Nigeria  Not Applicable              Sydney
1485     1486  United Arab Emirates         Bulacan               Dubai
1488     1489          Saudi Arabia  Not Applicable              Riyadh
1490     1491                  Peru  Not Applicable      Cerro De Pasco
1557     1558                 Kenya         Isabela      Not Applicable
1558     1559               Algeria  Not Applicable      Not Applicable
1561     1562               Vietnam         Bulacan         Ho Chi Minh
1579     1580                 Ghana           Accra               Accra
1591     1592                 India          Taguig      Not Applicable
1606     1607                 Spain  Not Applicable      Not Applicable
1635     1636                 Egypt  Not Applicable               Cairo
1707     1708               Nigeria  Not Applicable      Not Applicable
1728     1729               Nigeria  Not Applicable               Lagos

In [70]:
# 8c. Check ph cities
df_ph_grp = df_loc_new[df_loc_new['country'] == "Philippines"].groupby(['country','city_ph', 'city_non_ph'])['resp_id'].count().reset_index()
df_ph_grp.rename(columns = {"resp_id": "count_resp"}, inplace = True)
df_ph_grp.to_csv(location_dir/"df_ph_grp.csv", index=False)
print("Date and Time: ", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print("~"*50)
df_ph_grp

Date and Time:  2026-03-10 12:51:26
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

         country        city_ph        city_non_ph  count_resp
0    Philippines          Aklan     Not Applicable           1
1    Philippines          Albay     Not Applicable          10
2    Philippines        Aleosan     Not Applicable           1
3    Philippines        Angeles     Not Applicable           1
4    Philippines         Angono     Not Applicable           3
..           ...            ...                ...         ...
184  Philippines          Virac     Not Applicable           1
185  Philippines  Western Samar     Not Applicable           1
186  Philippines       Zambales     Not Applicable           5
187  Philippines       Zambales  Prefer Not To Say           1
188  Philippines      Zamboanga     Not Applicable          11

[189 rows x 4 columns]

In [71]:
# 8d. Cannot force city_non_ph to be "Not Applicable" if country = Philippines
# Lots of 'Prefer Not To Say', likely working overseas

overseas = df_ph_grp[df_ph_grp['city_non_ph'] == "Prefer Not To Say"]
print("Date and Time: ", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print("~"*50)
overseas

Date and Time:  2026-03-10 12:51:34
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

         country         city_ph        city_non_ph  count_resp
6    Philippines        Antipolo  Prefer Not To Say           1
19   Philippines        Batangas  Prefer Not To Say           1
32   Philippines          Butuan  Prefer Not To Say           1
38   Philippines  Cagayan De Oro  Prefer Not To Say           2
44   Philippines        Caloocan  Prefer Not To Say           2
53   Philippines          Cavite  Prefer Not To Say           1
55   Philippines            Cebu  Prefer Not To Say           1
75   Philippines     Iligan City  Prefer Not To Say           1
105  Philippines     Mandaluyong  Prefer Not To Say           2
127  Philippines  Not Applicable  Prefer Not To Say           1
129  Philippines     Nueva Ecija  Prefer Not To Say           3
135  Philippines        Pampanga  Prefer Not To Say           1
138  Philippines      Pangasinan  Prefer Not To Say           1
176  Philippines          Tarlac  Prefer Not To Say           1
187  Philippines        Zambales  Prefer Not To Say           1

In [76]:
# 8e. Check city_non_ph if complete for geocoding
df_non_ph_grp = df_loc_new[df_loc_new['country'] != "Philippines"].groupby(['country','city_non_ph', 'city_ph'])['resp_id'].count().reset_index()
df_non_ph_grp.to_csv(location_dir/"df_non_ph_grp_before_lookup.csv", index = False)
print("Date and Time: ", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print("~"*50)
df_non_ph_grp

Date and Time:  2026-03-10 13:03:07
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

                 country         city_non_ph         city_ph  resp_id
0                Algeria      Not Applicable  Not Applicable        1
1             Bangladesh            Barishal  Not Applicable        1
2               Cambodia          Phnom Penh  Not Applicable        1
3               Cameroon              Douala  Not Applicable        1
4                 Canada      Not Applicable        Caloocan        1
5                 Canada   Prefer Not To Say  Not Applicable        1
6                 Canada              Regina  Not Applicable        1
7                  Congo            Kinshasa        Kinshasa        1
8                  Egypt          Alexandria      Alexandria        1
9                  Egypt               Cairo           Cairo        1
10                 Egypt               Cairo  Not Applicable        3
11                 Egypt      Not Applicable  Not Applicable        1
12                 Ghana               Accra           Accra        1
13                 India      Not Applicable          Taguig        1
14                Jordan               Amman           Amman        1
15                 Kenya      Not Applicable         Isabela        1
16              Malaysia        Kuala Lumpur  Not Applicable        1
17                 Nepal           Kathmandu  Not Applicable        1
18                 Nepal      Not Applicable  Not Applicable        1
19               Nigeria          Benin City  Not Applicable        1
20               Nigeria               Lagos  Not Applicable        2
21               Nigeria      Not Applicable  Not Applicable        2
22               Nigeria              Sydney  Not Applicable        1
23               Nigeria             Ughelli  Not Applicable        1
24                Norway                Oslo  Not Applicable        1
25              Pakistan               Diplo           Diplo        1
26                  Peru      Cerro De Pasco  Not Applicable        1
27                  Peru               Pasco  Not Applicable        1
28          Saudi Arabia              Jeddah  Not Applicable        1
29          Saudi Arabia                 KSA         Bulacan        1
30          Saudi Arabia              Riyadh  Not Applicable        1
31          South Africa           Cape Town       Cape Town        1
32           South Korea       Cheongju City     South Korea        1
33                 Spain      Not Applicable  Not Applicable        1
34              Thailand             Bangkok  Not Applicable        1
35                   Uae               Dubai  Not Applicable        1
36                Uganda      Not Applicable  Not Applicable        1
37                Uganda  Soroti City Uganda  Not Applicable        1
38  United Arab Emirates           Abu Dhabi         Aleosan        1
39  United Arab Emirates               Dubai         Bulacan        1
40  United Arab Emirates               Dubai  Not Applicable        1
41  United Arab Emirates                 UAE  Not Applicable        1
42        United Kingdom              London  Not Applicable        1
43        United Kingdom           Newcastle  Not Applicable        1
44        United Kingdom      Not Applicable  Not Applicable        1
45         United States          Alexandria         Aleosan        1
46         United States              Kansas  Not Applicable        1
47               Vietnam         Ho Chi Minh         Bulacan        1
48                 Yemen              Sana'A  Not Applicable        1

In [48]:
# 8f. Capital lookup for missing city_non_ph
import pandas as pd
df_non_ph_grp = pd.read_csv(location_dir/"df_non_ph_grp_before_lookup.csv")

# Extract all unique countries
unique_countries = sorted(df_non_ph_grp["country"].dropna().unique())

# Lookup dictionary only for missing cities
capital_lookup = {
    "Algeria": "Algiers",
    "Bangladesh": "Dhaka",
    "Cambodia": "Phnom Penh",
    "Cameroon": "Yaounde",
    "Canada": "Ottawa",
    "Congo": "Kinshasa",
    "Egypt": "Cairo",
    "Ghana": "Accra",
    "India": "New Delhi",
    "Jordan": "Amman",
    "Kenya": "Nairobi",
    "Malaysia": "Kuala Lumpur",
    "Nepal": "Kathmandu",
    "Nigeria": "Abuja",
    "Norway": "Oslo",
    "Pakistan": "Islamabad",
    "Peru": "Lima",
    "Saudi Arabia": "Riyadh",
    "South Africa": "Pretoria",
    "South Korea": "Seoul",
    "Spain": "Madrid",
    "Thailand": "Bangkok",
    "Uae": "Abu Dhabi",
    "Uganda": "Kampala",
    "United Arab Emirates": "Abu Dhabi",
    "United Kingdom": "London",
    "United States": "Washington",
    "Vietnam": "Hanoi",
    "Yemen": "Sanaa",
}

# Find missing countries
missing = [c for c in unique_countries if c not in capital_lookup]

if len(missing) == 0:
    print("All countries are in the lookup dictionary.")
else:
    print ("Some countries are missing from the lookup")
    for c in missing:
        print("-", c)

# Stop here and manually update capital_lookup
print("Date and Time: ", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print("~"*50)

All countries are in the lookup dictionary.
Date and Time:  2026-03-10 10:59:04
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [65]:
# 8g. Replace missing or suppressed city_non_ph values with capital
# Geocode non ph cities -> wait 35 mins or less

df_non_ph_grp["city_non_ph"] = df_non_ph_grp.apply(
    lambda row: capital_lookup[row["country"]]
    if row["city_non_ph"] in ["Not Applicable", "Prefer Not To Say"]
    else row["city_non_ph"],
    axis=1
)

df_non_ph_grp.to_csv(location_dir/"df_non_ph_grp_after_lookup.csv", index = False)
df_non_ph_grp.to_csv(location_dir/"df_non_ph_grp.csv", index = False)
print("Missing values replaced with capitals")
print("Date and Time: ", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print("~"*50)
df_non_ph_grp

Missing values replaced with capitals
Date and Time:  2026-03-10 12:22:59
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

                 country         city_non_ph  resp_id
0                Algeria             Algiers        1
1             Bangladesh            Barishal        1
2               Cambodia          Phnom Penh        1
3               Cameroon              Douala        1
4                 Canada              Ottawa        1
5                 Canada              Ottawa        1
6                 Canada              Regina        1
7                  Congo            Kinshasa        1
8                  Egypt          Alexandria        1
9                  Egypt               Cairo        4
10                 Egypt               Cairo        1
11                 Ghana               Accra        1
12                 India           New Delhi        1
13                Jordan               Amman        1
14                 Kenya             Nairobi        1
15              Malaysia        Kuala Lumpur        1
16                 Nepal           Kathmandu        1
17                 Nepal           Kathmandu        1
18               Nigeria          Benin City        1
19               Nigeria               Lagos        2
20               Nigeria               Abuja        2
21               Nigeria              Sydney        1
22               Nigeria             Ughelli        1
23                Norway                Oslo        1
24              Pakistan               Diplo        1
25                  Peru      Cerro De Pasco        1
26                  Peru               Pasco        1
27          Saudi Arabia              Jeddah        1
28          Saudi Arabia                 KSA        1
29          Saudi Arabia              Riyadh        1
30          South Africa           Cape Town        1
31           South Korea       Cheongju City        1
32                 Spain              Madrid        1
33              Thailand             Bangkok        1
34                   Uae               Dubai        1
35                Uganda             Kampala        1
36                Uganda  Soroti City Uganda        1
37  United Arab Emirates           Abu Dhabi        1
38  United Arab Emirates               Dubai        2
39  United Arab Emirates                 UAE        1
40        United Kingdom              London        1
41        United Kingdom           Newcastle        1
42        United Kingdom              London        1
43         United States          Alexandria        1
44         United States              Kansas        1
45               Vietnam         Ho Chi Minh        1
46                 Yemen              Sana'A        1

# Geocode 1.non ph, 2. ph cities → combine

In [ ]:
# 8h. Geocode non ph cities
# ~~~~~~~~~~~~~~~~~~~~~~~~~
# Import geopy
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

# Initialize geocoder
geolocator = Nominatim(user_agent="non_ph_geocoder")
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1.5)

# Extract unique cities for geocoding
unique_cities = df_non_ph_grp["city_non_ph"].dropna().unique()

# Prepare list for results
geo_results = []

for city in unique_cities:
    query = f"{city}"
    location = geocode(query)

    if location:
        geo_results.append(
            {
                "city_non_ph": city,
                "latitude": location.latitude,
                "longitude": location.longitude
            }
        )
    else:
        geo_results.append(
            {
                "city_non_ph": city,
                "latitude": None,
                "longitude": None
            }
        )

# Convert geocoding results to dataframe
df_geo = pd.DataFrame(geo_results)

# Merge coordinates back into main dataframe
df_non_ph_geo = df_non_ph_grp.merge(df_geo, on="city_non_ph", how="left")
df_non_ph_geo = df_non_ph_geo.rename(columns={"resp_id": "count_resp"})

# Export final geocoded file
df_non_ph_geo.to_csv(location_dir/"df_non_ph_geo.csv", index=False)

print("Date and Time: ", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print("Need human check because of geopy mistakes.")
print("~"*50)
df_non_ph_geo

In [77]:
# 8i. Geocode ph cities
# The whole process takes 4-5 mins

# Import geopy
import pandas as pd
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

df_ph_grp = pd.read_csv(location_dir/"df_ph_grp.csv")

# Initialize geocoder
geolocator = Nominatim(user_agent="ph_city_geocoder")

# Rate limiter: 1 request per second
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1.5)

# Extract unique PH cities
unique_cities = df_ph_grp["city_ph"].dropna().unique()

# Prepare list for results
geo_results = []

for city in unique_cities:
    query = f"{city}, Philippines"
    location = geocode(query)

    if location:
        geo_results.append(
            {
                "city_ph": city,
                "latitude": location.latitude,
                "longitude": location.longitude,
            }
        )
    else:
        geo_results.append(
            {
                "city_ph": city,
                "latitude": None,
                "longitude": None,
            }
        )

# Convert geocoding results to dataframe
df_geo = pd.DataFrame(geo_results)

# Merge coordinates back into grouped dataframe
df_ph_geo = df_ph_grp.merge(df_geo, on="city_ph", how="left")

# Export final geocoded file
df_ph_geo.to_csv(location_dir / "df_ph_geo.csv", index=False)


print("Date and Time: ", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
print("Need human check because of geopy mistakes.")
print("~"*50)
df_ph_geo

Date and Time:  2026-03-10 13:10:41
Need human check because of geopy mistakes.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

,country,city_ph,city_non_ph,count_resp,latitude,longitude
0,Philippines,Aklan,Not Applicable,1,11.629789,122.248118
1,Philippines,Albay,Not Applicable,10,13.216667,123.550000
2,Philippines,Aleosan,Not Applicable,1,7.158581,124.577400
3,Philippines,Angeles,Not Applicable,1,15.138935,120.587532
4,Philippines,Angono,Not Applicable,3,14.525848,121.152968
...,...,...,...,...,...,...
184,Philippines,Virac,Not Applicable,1,13.580359,124.231203
185,Philippines,Western Samar,Not Applicable,1,11.833333,125.000000
186,Philippines,Zambales,Not Applicable,5,15.230000,120.120000
187,Philippines,Zambales,Prefer Not To Say,1,15.230000,120.120000
188,Philippines,Zamboanga,Not Applicable,11,18.188871,120.547657

In [80]:
# 8i. Clean and combine ph and non ph dfs

# Create cleaned files for folium
df_ph_geo_clean = df_ph_geo.dropna(subset=["latitude", "longitude"])
df_ph_geo_clean.to_csv(location_dir/ "df_ph_geo_clean.csv", index = False)

df_non_ph_geo_clean = df_non_ph_geo.dropna(subset=["latitude", "longitude"])
df_non_ph_geo_clean.to_csv(location_dir/ "df_non_ph_geo_clean.csv", index = False)

df_ph_geo_clean = pd.read_csv(location_dir/"df_ph_geo_clean.csv")
df_non_ph_geo_clean = pd.read_csv(location_dir/"df_non_ph_geo_clean.csv")

# Enforce identical column order and names
required_cols = [
    "country",
    "city_ph",
    "city_non_ph",
    "count_resp",
    "latitude",
    "longitude"
]

df_ph_geo_clean= df_ph_geo_clean[required_cols]
df_non_ph_geo_clean = df_non_ph_geo_clean[required_cols]

# Concatenate
df_all_geo_clean = pd.concat([df_ph_geo_clean, df_non_ph_geo_clean], axis=0, ignore_index=True)

# Export final combined file
df_all_geo_clean.to_csv(location_dir/"df_all_geo_clean.csv", index=False)

print("Ph and Non-Ph geocoded files combined.")
print("Date and Time: ", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

# Manually clean the final concatenated geo file, not upstream files
# Zamboanga is located at latitude 6.91028 and longitude 122.07389.

Ph and Non-Ph geocoded files combined.
Date and Time:  2026-03-10 13:15:13

"""
### Optional - Prework in Powershell Terminal,  Only if using Display map m.
PS 
Powershell navigate to current working directory.
command 'jupyter trust survey_data_cleaning.ipynb'
Result:
Signing notebook: survey_data_cleaning.ipynb
"""

In [17]:
# 8j. Use folium to create an interactive map for df_all_geo_clean
# df_all_geo_clean → location_map_2026.html
import folium 
import pandas as pd

df_all_geo_clean = pd.read_csv("location_dir/df_all_geo_clean.csv")
# Create a map centered on the Philippines
m = folium.Map(location=[12.8797, 121.7740], zoom_start=6)

# Add markers for each city
for _, row in df_all_geo_clean.iterrows():

    # Choose the correct label
    label = row["city_ph"] if row["country"] == "Philippines" else row["city_non_ph"]

    folium.Marker(
        location=[row["latitude"], row["longitude"]],
        popup=label,
        tooltip=label,
        zoom_start  = 6,
        tiles = "CartoDB Positron"
    ).add_to(m)

# Display the map  (Optional - need to restart after Powershell command.))
# m   

# 8k. Using m.save to save the map
m.save("location_dir/location_map_2026.html")

In [15]:
# Visually inspect anomalies
# Replace erroneous latitude and longitude for : 
#   Zamboanga, 6.91028, 122.07389
#   Quezon province,  13.9358, 121.6129
#   Egypt, Alexandria, 31.205753,29.924526
#   United States,Alexandria,1,38.8048,-77.0469
#   Peru,Not Applicable,Pasco,1,-10.6835926,-76.2561123

##### STOP HERE: Manually clean df_all_geo_clean.csv here. 
- Delete previous map.html file.
- Then re-run folium.

# 9. Export data mart sql versions
- df_single_with_grps merge with all df_exploded as list

In [18]:
# 9a. List of all exploded dfs
import pandas as pd
import os
from pathlib import Path
import numpy as np

# Retrieve all the csv outputs
csv_outputs_dir = Path("csv_outputs_dir")
csv_outputs_dir.mkdir(exist_ok=True)


exploded_filepaths = [
    x for x in csv_outputs_dir.iterdir()
    if x.name.endswith("_exploded_cleaned.csv")
]

exploded_filepaths

[WindowsPath('csv_outputs_dir/ai_tools_exploded_cleaned.csv'),
 WindowsPath('csv_outputs_dir/attended_inperson_exploded_cleaned.csv'),
 WindowsPath('csv_outputs_dir/attended_online_exploded_cleaned.csv'),
 WindowsPath('csv_outputs_dir/busint_exploded_cleaned.csv'),
 WindowsPath('csv_outputs_dir/cloudplat_exploded_cleaned.csv'),
 WindowsPath('csv_outputs_dir/dep_init_exploded_cleaned.csv'),
 WindowsPath('csv_outputs_dir/digitools_exploded_cleaned.csv'),
 WindowsPath('csv_outputs_dir/generaltools_exploded_cleaned.csv'),
 WindowsPath('csv_outputs_dir/hardware_exploded_cleaned.csv'),
 WindowsPath('csv_outputs_dir/ingestion_exploded_cleaned.csv'),
 WindowsPath('csv_outputs_dir/orchest_exploded_cleaned.csv'),
 WindowsPath('csv_outputs_dir/otherfb_exploded_cleaned.csv'),
 WindowsPath('csv_outputs_dir/restofrole_exploded_cleaned.csv'),
 WindowsPath('csv_outputs_dir/spneeds_exploded_cleaned.csv'),
 WindowsPath('csv_outputs_dir/storage_exploded_cleaned.csv'),
 WindowsPath('csv_outputs_dir/successmethod_exploded_cleaned.csv'),
 WindowsPath('csv_outputs_dir/transform_exploded_cleaned.csv'),
 WindowsPath('csv_outputs_dir/volunteer_exploded_cleaned.csv'),
 WindowsPath('csv_outputs_dir/warehs_exploded_cleaned.csv'),
 WindowsPath('csv_outputs_dir/whatused_exploded_cleaned.csv')]

In [24]:
# 9b. Dictionary of all  df_exploded files
# Key is {col} file, value is a dataframe
dfs_exploded = {}

for path in exploded_filepaths:
    col = path.stem.replace("_exploded_cleaned", "")
    df = pd.read_csv(path)
    dfs_exploded[col] = df

dfs_exploded.keys()

dict_keys(['ai_tools', 'attended_inperson', 'attended_online', 'busint', 'cloudplat', 'dep_init', 'digitools', 'generaltools', 'hardware', 'ingestion', 'orchest', 'otherfb', 'restofrole', 'spneeds', 'storage', 'successmethod', 'transform', 'volunteer', 'warehs', 'whatused'])

In [27]:
dfs_exploded["ai_tools"].head()

   resp_id ai_tools
0        1  Chatgpt
1        2  Chatgpt
2        2  Copilot
3        3  Chatgpt
4        3  Copilot

In [28]:
# 9c. Combine everything into duckdb with df_single_with_grps

import duckdb
con = duckdb.connect("survey2026.duckdb")

#  Store all multi-response dfs as tables
for name, df in dfs_exploded.items():
    con.register("tmp", df)
    con.execute(f"CREATE OR REPLACE TABLE {name} AS SELECT * FROM tmp")

# Store df_single_with_grps
df_single_with_grps = pd.read_csv(csv_outputs_dir/"df_single_with_grps.csv")
con.register("tmp", df_single_with_grps)
con.execute("CREATE OR REPLACE TABLE df_single_with_grps AS SELECT * FROM tmp")


# Retrieve the combined ph and non ph geo coded file 
location_dir = Path("location_dir")
location_dir.mkdir(exist_ok = True)

# Store df_all_geo_clean
df_all_geo_clean = pd.read_csv(location_dir/"df_all_geo_clean.csv")
con.register("tmp", df_all_geo_clean)
con.execute("CREATE OR REPLACE TABLE df_all_geo_clean AS SELECT * FROM tmp")

# Inspect all tables
con.execute("SHOW TABLES").df()

                   name
0              ai_tools
1     attended_inperson
2       attended_online
3                busint
4             cloudplat
5              dep_init
6      df_all_geo_clean
7   df_single_with_grps
8             digitools
9          generaltools
10             hardware
11            ingestion
12              orchest
13              otherfb
14           restofrole
15              spneeds
16              storage
17        successmethod
18                  tmp
19            transform
20            volunteer
21               warehs
22             whatused

In [ ]:
# 9d. close the connection
con.close()

# Log
import datetime
print("Duckdb created. Connection closed.")
print("Date and Time:", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

In [32]:
# Log
import datetime
print("Duckdb created. Connection closed.")
print("Date and Time:", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

Duckdb created. Connection closed.
Date and Time: 2026-03-10 14:42:55

In [36]:
#9e. Create a sqlite version for side explorations
# A lot smaller than duckdb since it has no metadata

import duckdb
con = duckdb.connect("survey2026.duckdb")

con.execute("DETACH DATABASE IF EXISTS sqlite_db")
con.execute("ATTACH 'survey2026.sqlite' AS sqlite_db (TYPE sqlite)")
tables = con.execute("SHOW TABLES").fetchall()
for (table_name,) in tables:
    con.execute(f"DROP TABLE IF EXISTS sqlite_db.{table_name}")
    con.execute(f"""
        CREATE TABLE sqlite_db.{table_name} AS
        SELECT * FROM {table_name}
    """)
con.close()

# Log
print("Sqlite created. Connection closed.")
print("Date and Time:", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

Sqlite created. Connection closed.
Date and Time: 2026-03-10 14:47:53

# 10.  Export data mart excel version for_tableau.xlsx file

In [37]:
import pandas as pd
from pathlib import Path
import shutil

# Directories
csv_outputs_dir = Path("csv_outputs_dir")
location_dir = Path("location_dir")

final_outputs_dir = Path("final_outputs_dir")
final_outputs_dir.mkdir(exist_ok=True)

# 1. Identify final csv files
single_file = csv_outputs_dir / "df_single_with_grps.csv"
geo_file = location_dir / "df_all_geo_clean.csv"
exploded_files = list(csv_outputs_dir.glob("*_exploded_cleaned.csv"))

files_to_copy = [single_file, geo_file] + exploded_files

# 2. Copy final csv files to final_outputs
for f in files_to_copy:
    if f.exists():
        shutil.copy(f, final_outputs_dir / f.name)
    else:
        print(f"Missing file:", f)

# 3. Build Excel workbook from the final CSVs
xlsx_path = final_outputs_dir / "for_tableau.xlsx"

with pd.ExcelWriter(xlsx_path, engine="xlsxwriter") as writer:
    for f in files_to_copy:
        if f.exists():
            df = pd.read_csv(f)
            sheet_name = f.stem[:31]  # Excel sheet name limit
            df.to_excel(writer, sheet_name=sheet_name, index=False)

print("for_tableau.xlsx created in final_outputs directory.")

for_tableau.xlsx created in final_outputs directory.